### ISSUE TITLE
automatic point calculation for match

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#100]
As a league participant,
I want to see the points each player of a match received, without entering them myself
So that correctness is ensured and effort removed.

**Acceptance Criteria**

- [x] The point rules are determined in the event creation(for win, lose, and draw). The winner of a game is the player with the most goals (basic rule for now, later on possibly with minimal goal difference ). The winner of a match is the player who won the most games. Points should be given accordingly and should be displayed in the last column.
- [x] The  Spielplan should calculate the points distribution depending on the outcome of the match. 

- [x] When the points are calculated I can see them in the boxes in which I can normally enter the points but still have the functionality to reedit them manually

**Comment by PoJo93** [comment]
Nice work! Even though there is still one issue. When I put in the result the points are calculated. When I change the outcome of the game after that there is no recalculation. @nikriek

**Comment by PoJo93** [comment]
Already good but points are displayed in the wrong order

**Comment by nikriek** [comment]
Solved :)
