### ISSUE TITLE
league table should display image of player/team

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#102]
As a league participant
I want to see my profile picture as small icon on the league table
So that i can easily find my self and other friends in the table

Addition to #101 

Acceptance Criteria

- [ ] my profile picture should be displayed in league table on the left side of my name
- [ ] a small circle cutout should be displayed
- [ ] it should change when I change my profile picture
- [ ]  if I have no picture there should be an empty space to ensure correct alignment of the starting position of the player names
- [ ] should work for teams and single players

just like 
![image](https://user-images.githubusercontent.com/29160369/33048793-f8698f18-ce5c-11e7-8d70-c2d9f251bfb0.png)
