### ISSUE TITLE
Multiple page playing schedule

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#105]
As a player in a league
I want to see the Spielplan split in multiple tables, each for one Spieltag
In order to inform myself without lots of searching about upcoming matches

Acceptance criteria

- [ ] For each Spieltag a individual table (Spielplan) is shown with all matches
- [ ] only one Spieltag Spielplan is shown at a time
- [ ] on the top of the Spielplan table the Spieltag should be displayed
- [ ] with back and forward buttons you can switch the Spieltage and change the displayed Spielplan
- [ ] when visiting the Spielplan the current Spieltag of the running event is automatically displayed
- [ ] it is only possible to enter match results for the current Spieltag
- [ ] the existing Spielplan with all pages should remain the way it is, there will be two modes for the Spielplan, which can be switched with the switch button on top

Mockup:

![image](https://user-images.githubusercontent.com/29160369/33064185-21d6d124-cea5-11e7-8c36-d06fdb170379.png)
