### ISSUE TITLE
Leave team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#122]
As **Team Member** I can leave any of my teams.

Acceptance criteria:

- [x] 	There is a button on the team page "Team verlassen"
- [x] 	Every team member can leave a team
- [x] 	After clicking the button User receives request for confirmation (see mockup)
- [x] 	Team Owner can't leave the team if he is single team owner there

<img width="342" alt="screen shot 2017-11-25 at 10 07 10" src="https://user-images.githubusercontent.com/27727717/33229090-6c8a0af8-d1c8-11e7-945b-5f1404b5b95f.png">

**Comment by lheilmann** [comment]
Depends on #23

**Comment by lheilmann** [comment]
**Development tasks**:

- [x] Use existing route for deleting a team membership in `TeamsController`- consider migrating functionality to `TeamUserController` to encapsulate actions concerning team ownership and team membership
- [x] Add a button on `teams/show` page routing to the specific route (see above)
- [x] Add creation of basic jquery popup after button click (see examples)
- [x] Check abilities for members with team ownership
- [x] Check complete test coverage

**Comment by lheilmann** [comment]
**Details for Review**

![screen shot 2017-12-12 at 00 12 22](https://user-images.githubusercontent.com/18228544/33858740-361b1974-ded1-11e7-85c9-c32bd54eecb5.png)

- Button is located on bottom of page next to „Löschen"
- Button is only visible, if user is authorized to leave the team
