### ISSUE TITLE
Design of Team Page

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#123]
As Team Owner I have a **simple, intuitive team page** in order to manage my team.

Acceptance criteria (please consider mockup):

- [ ] Team page includes table with team members 
- [ ] Members' table has simple columns and action panel
- [ ] Team Name is noticeable 
- [ ] Team Description is part of the page
- [ ] There are buttons "Add player", "Leave team",  "Edit", "Delete team"
- [ ] In Edit modus instead of Edit button user sees "Cancel" and "Save"

**Assign to team @zhamanakov** 

<img width="550" alt="screen shot 2017-11-25 at 10 21 12" src="https://user-images.githubusercontent.com/27727717/33229202-637c7c50-d1ca-11e7-8bf4-24d002d30210.png">
