### ISSUE TITLE
Send email to team members

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#124]
As Team Member I can send **emails** to other team members.

**Acceptance criteria:**

- [x] Every team member has rights to send message to other team members
- [x] Team member can choose group of players to send group email
- [x] As recipients are chosen and the button is clicked, the window of mailing program opens
- [x] If user has no mailing program, user can send emails via owa/etc. Recipients'adresses are shown in To: field

**Comment by bakoe** [comment]
@svitlanakalancha:

While working on this issue, I noticed that the ”Bitte wähle“ and ”Aktionen“ columns as well as the “Wende folgende Aktion auf Ausgewählte an:” row are displayed even if the user currently logged **cannot** perform any action on any team member (because he is not a team member). See the following screenshot for explanation:

<img width="1233" alt="bildschirmfoto 2018-01-14 um 13 18 16" src="https://user-images.githubusercontent.com/807665/34915861-e04fac4a-f92d-11e7-9da2-a5dc69fce086.png">

I changed the view to only show the columns and rows mentioned when the user currently logged in **can** perform any action on any team member. See the following screenshot for explanation:

<img width="1247" alt="bildschirmfoto 2018-01-14 um 13 19 35" src="https://user-images.githubusercontent.com/807665/34915866-fe145b9a-f92d-11e7-951d-4fbc56c73953.png">

Now my question: Is it okay for you to have this ”bug“ (if it even was one?) fixed within this issue or do you want to have a separate issue for this bug? If I should revert the changes regarding the rendering of these columns and rows, it would be a matter of a minute – so it would be no problem for me development-wise to revert the changes I made.

**Comment by svitlanakalancha** [comment]
@bakoe as discussed, it is ok. Thank you!

**Comment by bakoe** [comment]
Actual time I invested in this issue: 1 h
