### ISSUE TITLE
Create rankings for event (League)

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#125]
As Event participant I can **track the results** of my event in order to **evaluate** them.

**ACCEPTANCE CRITERIA**

_Frontend_

- [ ] Each event has separate ranking page connected to the event page (general ranking for all events is out of scope)
- [ ] Page includes the table with results. The table has following columns:
- Rang, Team, Spielanzahl, Gewonnen, Unentschieden, Verloren, Tore (geschossene/verlorene), Anzahl von Punkten
- [ ] Players or teams originate from participation list of the event

_Backend_

- [ ] Results of the played matches are automatically tracked and counted in the ranking table
- [ ] Results of the match are automatically translated into the points. Points assignment depends on match system. Typically it looks like this:
> the winner receives 3 points,
> even score - each team 1 point,
> looser - 0 points
- [ ] if 2 players/teams have equal amount of points by the end of event, the winner is determined by counting amount of goals. **NOTE:** works differently for "Schweizer System"
- [ ] The table should be automatically sorted by achieved points
- [ ] The winner is placed on the top of the table
- [ ] Ranking table can't be edited manually

**NOTE**
Consider different systems by leagues and tournaments

**OUT OF SCOPE**
Implementation of specific counting systems for different kinds of sport

<img width="548" alt="screen shot 2017-11-24 at 15 53 46" src="https://user-images.githubusercontent.com/27727717/33229635-7b1d465c-d1d2-11e7-9b47-d724e3292d8c.png">

<img width="404" alt="screen shot 2017-11-25 at 10 57 10" src="https://user-images.githubusercontent.com/27727717/33229637-82420bca-d1d2-11e7-9da4-7cb18d8d717b.png">

**Comment by birneamstiel** [comment]
**Development Tasks**

- [ ] Create `GET :event_ranking` route to `routes.rb`
  - Add tests for route
- [ ] Create controller action `events_controller#ranking`
  - Check wether our event's participants are *teams* or *individual players* (following points assume we have teams, logic for individual players has to be adjusted)
  - Check wether our event's type is *league* or *tournament* (following points assume event type is league. Logic for tournament has to be adjusted, do tournaments even have rankings?)
  - Calculate necessary columns by iterating over `teams` and `matches` (something like in the pseudocode listing below)
  - Sort teams by points
    - Pay attention to ACs when two teams have the same amount of points
  - Come up with a way to deliver calculated data to view (maybe create instance variable?) and to store the calculated fields per team (simple array, [struct](http://ruby-doc.org/core-2.2.0/Struct.html), etc.) 
  - Add tests for method `ranking`
``` ruby
# this is a first approach for calculating the necessary data fields per team given that
# our event consists of teams (not individual players)

FOR EACH event.teams AS team DO
  # intersect team.home_matches with event.matches
  FOR EACH team.home_matches AS home_match DO
    match_count++
    IF home_match.has_winner?
      IF home_match.winner == team
        won_count++
      ELSE
        lost_count++
      END
    ELSE
      draw_count++
    END
    goals += home_match.score_home
    goals_against += home_match.score_away
    points += home_match.points_home
  END

  FOR EACH team.away_matches AS away_match DO
    match_count++
    IF away_match.has_winner?
      IF away_match.winner == team
        won_count++
      ELSE
        lost_count++
      END
    ELSE
      draw_count++
    END
    goals += away_match.score_away
    goals_against += away_match.score_home
    points += home_match.points_away
  END
  
  difference = goals - goals_against
  # now local variables have to be wrapped into some data structure
END
# data has to be sorted and passed to the view afterwards
```
 
- [ ] Create `views/events/ranking.html.erb` and display data calculated in `events_controller#ranking`
  - Add tests for view

**Comment by jonasnoki** [comment]
Test data illustration:
![image](https://user-images.githubusercontent.com/17072869/34697083-bcc9f650-f4d1-11e7-99ee-af6d507c5558.png)

**Comment by bakoe** [comment]
@jonasnoki While checking what caused the error in the sorting of the ranking entries, I noticed that there were some minor mistakes in the handwritten ranking table you supplied. However, the problem was caused by a variable not actually getting used in the EventsController. 

Anyhow, here's the corrected handwritten ranking table for future reference:
![34697083-bcc9f650-f4d1-11e7-99ee-af6d507c5558](https://user-images.githubusercontent.com/807665/34916128-22eb8010-f933-11e7-9413-04436dd6265c.png)

**Comment by svitlanakalancha** [comment]
Please delete "Zur Tabelle" button from tournament and ranking list

**Comment by lheilmann** [comment]
Sprint 3 Size: 20
Sprint 4 Size: 3

**Comment by svitlanakalancha** [comment]
@jonasnoki can you please set "Tordifferenz" as second criteria for winner determination?

**Comment by svitlanakalancha** [comment]
@jonasnoki please change column names in the table:
Tore -> Punkte
Gegentore -> Gegenpunkte
Punkte -> Ligapunkte

Thank you!

**Comment by jonasnoki** [comment]
Needed time: 4h

**Comment by bakoe** [comment]
Actual time I invested in this issue: 11 h
