### ISSUE TITLE
Evaluation and results tracking

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#126]
As Event participant I track the results of my event in order to define the winner.

**ACCEPTANCE CRITERIA**
- [ ] Results of the played matches are automatically tracked and counted in the ranking table
- [ ] Results of the match are automatically translated into the points. Points assignment depends on match system, defined by the team owner. See issue 95. Typically it looks like this:
> the winner receives 3 points,
> even score - each team 1 point,
> looser - 0 points
- [ ] if 2 players/teams have equal amount of points by the end of event, the winner is determined by counting amount of goals. **NOTE:** works differently for "Schweizer System"
- [ ] The table should be automatically sorted by achieved points
- [ ] The winner is placed on the top of the table
- [ ] Ranking table can't be edited manually

**Note:**
Consider different systems by leagues and tournaments

**OUT OF SCOPE**
Implementation of specific counting systems for different kinds of sport

**Comment by svitlanakalancha** [comment]
Points assignment should be stored in Match object. Currently not implemented.

**Comment by svitlanakalancha** [comment]
This US migrated to #125
