### ISSUE TITLE
Create ranking list

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#131]
**AS AN** organiser of ranking list
**I WANT TO** be able create new ranking list events
**SO THAT** people can find and participate at my ranking list event

## ACCEPTANCE CRITERIA
- [x] When creating a new event on the *create event* page a new event type should be shown "Ranking List" ("Rangliste" in German)
- [x] When the user picks this type of event following options should be available/unavailable:
  - [x] The metric for ranking (Elo, TrueSkill and Ration Win:Loss)
  - [x] The initial value for the metric (the value new users get when they join the event)
  - [x] There should be no deadline nor a start or end date
  - [x] Only single players are allowed, so there should be no option for team sport
  - [x] The other options remain as in issues #19

**Comment by GittiHab** [comment]
Mockups to this user story. The user first needs to select the event type before seeing event-specific options.
![create_ranking](https://user-images.githubusercontent.com/6453623/33240365-3a661268-d2b5-11e7-86a5-bcd84a2d16fe.jpg)

**Comment by GittiHab** [comment]
Please reference #129 to see other user stories which might intersect to this one

**Comment by GittiHab** [comment]
Die detaillierte Eventseite sollte nur die Ranking List Attribute anzeigen

<img width="1388" alt="screen shot 2017-12-18 at 16 36 35" src="https://user-images.githubusercontent.com/6453623/34113972-b6381536-e411-11e7-9dc6-1e114de9881f.png">

**Comment by GittiHab** [comment]
I can see that this is part of an issue of another team (#244) therefore everything seems fine.
