### ISSUE TITLE
Joining a ranking list

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#134]
**AS AN** user
**I WANT TO** be able to join a ranking list event
**SO THAT** I can participate in such events

## ACCEPTANCE CRITERIA
This is based on #85 
- [ ] There is no deadline so users can always join
- [ ] When the user joined the event via the join button the user is a participant of the ranking list
- [ ] New participants get the initial value of the metric of the ranking list

**Comment by GittiHab** [comment]
This basically already works.
