### ISSUE TITLE
Elo Ranking

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#136]
**AS AN** organiser of a ranking list event
**I WANT TO** be able to select elo ranking as a metric
**SO THAT** the users can be ranked by this metric

## ACCEPTANCE CRITERIA
- [x] When creating a new event of the type "Ranking List" there should be a metric option "Elo"
- [x] When a user added a new match to a ranking list event the system should calculate the new elo score of the participants based on the metric of the event
- [x] The new score is calculated based on the [elo number](https://en.wikipedia.org/wiki/Elo_rating_system)
- [x] The new score of each participant is saved so that it can be displayed in the event evaluation

**Comment by GittiHab** [comment]
k is always 32?

**Comment by GittiHab** [comment]
Why are the classical match options also shown for Elo-Rankinglists? They don't apply, right?
<img width="1233" alt="screen shot 2018-02-02 at 15 29 28" src="https://user-images.githubusercontent.com/6453623/35738050-ebb75038-082d-11e8-8104-59bb83106b64.png">

**Comment by GittiHab** [comment]
- [ ] So please add a field `k` to the form with default value 32 which the user can change to adjust the Elo-Function
- [ ] and hide the advanced match options as they don't apply

**Comment by pawelsoundso** [comment]
We can think about moving the selection of k into the advanced match options. Would that also suit your request? (instead of the current ones of course)

**Comment by GittiHab** [comment]
That would suit the requirements, since k is comparable to the points one receives when winning/loosing/...

**Comment by GittiHab** [comment]
Can we also hide the match type and win condition? They should always have the values 1 and *most wins* respectively. 
<img width="1225" alt="screen shot 2018-02-06 at 10 35 23" src="https://user-images.githubusercontent.com/6453623/35852145-67025c20-0b2a-11e8-88cb-21876b261875.png">

**Comment by pawelsoundso** [comment]
Is this asked for all types of ranking lists or only for those, with elo ranking?

**Comment by GittiHab** [comment]
For all

**Comment by GittiHab** [comment]
BTW, the current dev doesn't have your changes anymore @pawelsoundso

**Comment by GittiHab** [comment]
The start value can be empty, which leads to an error when joining the ranking list.

When editing a ranking list the start value is not displayed.
![screen shot 2018-02-08 at 15 52 18](https://user-images.githubusercontent.com/6453623/35979270-347af360-0ce8-11e8-9f69-b59cfc9c6844.png)
