### ISSUE TITLE
Simple ranking list metric

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#137]
**AS AN** organiser of a ranking list event
**I WANT TO** be able to select "Wins:Losses Ration" as a metric
**SO THAT** the users can be ranked by this metric

## ACCEPTANCE CRITERIA
- [ ] When creating a new event of the type "Ranking List" there should be a metric option "Wins:Losses Ratio"
- [ ] When a user added a new match to a ranking list event the system should calculate the new score of the participants based on the metric of the event
- [ ] The new score is calculated by dividing `#wins/(#wins+#losses)`
- [ ] The new score of each participant is saved so that it can be displayed in the event evaluation
