### ISSUE TITLE
Swiss system support

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#139]
As a event organizer
I want to create an event using the swiss system for match making
In order to ensure evenly matched player/team strengths in the games

https://de.wikipedia.org/wiki/Turnierform
https://de.wikipedia.org/wiki/Schweizer_System

Depends on implementation of #125 

**Acceptance criteria**
- [x] Selecting  "Schweizersystem" in create event Page #19 will create an event using the Swiss system
- [x]  After each game-day ("Spieltag") the upcoming matches for the next game-day will automatically be calculated
- [ ] These matches are calculated according to the swiss system
   - [x] Matches for the first game-day are random
   - [ ] For the next game-day the leading player plays against the second best, and so on
   - [ ] if there is no clear choice for a contender(for example multiple players ranked second), the selection is random
    - [ ] for starters there should be as many game-days as in a "jeder gegen jeden" so n-1 for n players
    - [ ] No two players play against each other twice

**Comment by MarcelSchmidberger** [comment]
whats the criteria for calculating the new gameday right know? I assume the new gameday is calculated as soon as the new gameday starts (so 00:01 Uhr of the startdate of the gameday)? This results in problems when I want all gamedays to happen at the same time.

![image](https://user-images.githubusercontent.com/29160369/35816348-c00244ba-0a9a-11e8-8b70-4020bbe779d6.png)

Now all gamedays are calculated at once, so the order of the "Spielpaarungen" is random. 
Would it be possible to add a button "calculate new gameday" which takes the ranking as it is at this moment and based on this ranking the new gameday is calculated? This button should only be visible by the admin or organizer. Th button is an additional means to calculate the new gameday. The new gamedays are calculated when the new gameday starts or the next gameday can be generated by pressing the button. How much work would this be to implement?

This could look like this

![image](https://user-images.githubusercontent.com/29160369/35816675-9b419bd4-0a9b-11e8-96a1-6aa132f80514.png)

**Comment by MarcelSchmidberger** [comment]
there seems to be a bug, when reloading the playing schedule after first generation results in an empty gameday 7 and all matches from this gameday are moved to gameday 8

![image](https://user-images.githubusercontent.com/29160369/35816850-11f9c882-0a9c-11e8-8e37-c9d31d40686a.png)

**Comment by MarcelSchmidberger** [comment]
I am uncertain whether thats an heroku issue but the loading times are pretty long. Not really for the generation of the playing schedule but rather for the visit after entering match results for example. Try here:
https://sport-portal-dev.herokuapp.com/events/2/schedule

Edit: Ok it seems to be a heroku think, the playingschedule of a double rund robin isnt any faster

**Comment by MarcelSchmidberger** [comment]
Is there a special reason why the order of the matches in one gameday changes after entering the match results?

It seems like the matches where entering results is still necessary are on the bottom and when their results are entered they come back in the order of their initial state(just after generation). Is this correct? If so nice feature! 

![image](https://user-images.githubusercontent.com/29160369/35826671-b0313608-0ab9-11e8-8238-523d6737605a.png)

![image](https://user-images.githubusercontent.com/29160369/35826698-c59d95e0-0ab9-11e8-9895-dbdbb7af83b7.png)

Example 2

![image](https://user-images.githubusercontent.com/29160369/35826872-61806168-0aba-11e8-9e68-19ed7cbcc635.png)


![image](https://user-images.githubusercontent.com/29160369/35826884-6f3b7b62-0aba-11e8-8213-3b242351452f.png)
