### ISSUE TITLE
double round-robin support

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#141]
As a event organizer
I want to create an event using the double round-robin(Hin und Rückrunde) for match making
In order to give everyone the opportunity of a rematch

This is system ins based on #35 ("Jeder gegen jeden")
The first half of the event ("Hinrunde") is simply a round-robin ("Jeder gegen jeden") The second half of the event ("Rückrunde") consists of rematches of the first half. Their order should be maintained and only home and away of Player1/Team1 and Player2/Team2 should be swaped.

Example.       Home       Away
Frist Game :  Player1 vs Player2
Second Game: Player2 vs Player1

**Acceptance Criteria**

- [ ] Selecting"Hin und Rückrunde" in create event Page #19 will create an event using the "Hin und Rückrunde" System
- [ ] everybody plays twice with everybody else
- [ ] The order of the matches in the first half and the second half of the event should be the same, only home and away should change
- [ ] this should already work with the joined players and teams (#128, #140)
- [ ] this should work with the multiple page playing schedule #105

**Comment by MarcelSchmidberger** [comment]
"Hinrunde" and "Rückrunde" should be displayed, so that User know when the second round starts

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by usame-algan** [comment]
Actual size: M
