### ISSUE TITLE
Danish system support

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#143]
As a event organizer
I want to create an event using the danish system for match making
In order to ensure evenly matched player/team strengths in the games

The Danish system 
http://petanque-turnier.de/?page_id=234

Depends on implementation of #125 

**Acceptance criteria**
- [ ] Selecting  "Dänisches System" in create event Page #19 will create an event using the Danish System
- [ ]  After each game-day ("Spieltag") the upcoming matches for the next game-day will automatically be calculated. This will extend the playing schedule by one day.
- [ ] These matches are cacluclated according to the danish system
   - [ ] Matches for the first game-day are random
   - [ ] For the next game-day the first plays with the second, the third plays with the fourth... 
   - [ ] if there is no clear choice for a contender(for example multiple players ranked second), the selection is random
    - [ ] for starters there should be as many game-days as in a "jeder gegen jeden" so n-1 for n players
