### ISSUE TITLE
Handle uneven player counts in playing schedule

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#144]
As an league organizer
I want to be able run my league with an uneven number of players
So that I dont have to find a additional participant to ensure an even player count in the last minute.

**Acceptance Criteria**
- [ ] if there is an uneven player count one of the players (randomly selected) will not play during each game-day. This should not happen multiple times to the same player if possible.
- [ ]  the player wont play in this game-day will have an empty match. So he is shown in the playing schedule in a match with no opponent and Points and Goals are set to zero.
- [ ] this should work in all possible game systems

**Comment by Askir** [comment]
actual size: XS
