### ISSUE TITLE
Enter Game-Day length in League configuration

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#145]
As league organizer
I want to select the length of the game days when configuring the league
In order to adjust the frequency of the matches

This is an addition to #19 

**Acceptance Criteria**

- [ ]  game day length can be in the league creation process
- [ ] is used correctly to calculate the new playing schedule

**Tasks**
- [ ]  Refactoring the Event model and its usage in a way that reduces dependencies between different event types
- [ ]  Add the options to the view page
- [ ]  Save it in the database
- [ ]  Modify the schedule view so that it displays gameday length appropriatly

**Comment by Askir** [comment]
@MarcelSchmidberger How exactly does this have an impact on the playing schedule? Should we display a timeframe for each gameday? Because the schedule generation will have to be the same regardless of how long a gameday actually lasts.

**Comment by MarcelSchmidberger** [comment]
The game-day length has no actual impact on the playing schedule calculation. But the time frame of each game-day should be displayed somewhere, so players know when they have to be done with their matches. 
This could look something like that: (please feel free to change the location of the time frame)

![image](https://user-images.githubusercontent.com/29160369/33422912-8b7ab906-d5b7-11e7-8157-839dbfea0aef.png)

**Comment by Askir** [comment]
I've been doing a larger refactor in the scope of this user story, which ended up being larger than expected because of it. 
While doing the refactor I decided to split up the create event pages into different pages for tournaments and leagues. I asked @MarcelSchmidberger before doing so, but now I'm getting different feedback from different teams. Can I have a clarification on this?

**Comment by MarcelSchmidberger** [comment]
Negative values should not be allowed and there needs to be an upper limit the process crashes when entering 10000000000 for the length

**Comment by MarcelSchmidberger** [comment]
it should also be shown in the event page

**Comment by Askir** [comment]
actual size (including refactoring): L
