### ISSUE TITLE
Propose a new Appointment

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#148]
AS a logged in user who is playing in a match
I WANT to propose a new appointment
TO be able to attend a game and have an appointment

ACCEPTANCE CRITERIA

When I have a match 

- [ ] I want to have a button "Neuen Termin vorschlagen"
- [ ] This will give me a popup in which I can enter
   -  Place
   -  Date and Time
- [ ] This will change the date which is currently the default date
