### ISSUE TITLE
Create new events

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#18]
**AS A** user after login
**I WANT TO** be able to create a new event
**SO THAT** I can organize a league or turnament

**ACCEPTANCE CRITERIA**

- [x] a button "create Event"  is located in the menu bar 
- [x] clicking this button will open the "create event page" 
- [x] on this page I can choose between the two basic event categories league and tournament

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.
