### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#182]
Design of Landing Page.

- all data (font-size, pics, colors are in Sketch)
- header is the same (see #183)
- Buttons "anmelden" bring user to his dashboard, if he is already signed-in, if not logged in --> sign up page
- FONT: ProximaNova
- all text is placeholder (Lorem Ipsum) except for header and footer (real text in #255)
- reuse components/styling from #185 
- not all links need to be functional yet
- font sizes (e.g. for `h1`) should be adapted application-wide depending on the screen size (ask @zhamanakov for details)

**Estimation: L**

- DESIGN UPDATED (!) 
- backgrounds in comments

 ![sms_01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fb99891cd2d2ebc3abaf51ab57f5973d047d317c05f3782387e72aba1579545f594eac42515a10adfbd82db4aa2e32db025fb28c341521842f1bbeb98415be04bb23894f85b7bd8d4dc1ee2f68.png)

 
The landing page is mobile-optimised:

![sms_04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fb99891cd2d7ebc3abaf51ab57f5973d047d317c05f3782387e72aba1579545f594eac42515a10adfbd82db4aa2e32db025fb28c341521842f1bbeb98515be04bb23894f85b7bf8a48c9ef2f68.png)

**Comment by stursberg** [comment]
[ProximaNova.zip](https://github.com/hpi-swt2/sport-portal/files/1515245/ProximaNova.zip)
[landing page.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46e49594278b8daecff9be44a11fbcd6395428792c07b7692ac7b629ef1128030b0d1bab135d5f42fcf98a22a3e26d72db5a19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bd894ec4e93c27e3828d4f2c53.zip)

**Comment by jak-ing** [comment]
**Estimation: L**

**Comment by jkbe** [comment]
Depends on #185 for reusable components.

**Comment by jkbe** [comment]
New pictures without licensing problems to come tonight.

**Comment by stursberg** [comment]
![background1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ea9599288591a69ae7bb12e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb29814e80b7bf8b45c9ea3921ef8d8e5d73.png)

![background2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ea9599288591a69ae7bb11e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb27814e80b7bf8b45c9ea3b21e78b895d73.png)


![background3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ea9599288591a69ae7bb10e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb26814e80b7bf8b45c9ea3920e48b8d5d73.png)


![background4.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ea9599288591a69ae7bb17e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb29814e80b7bf884cc0e83c23e28d895d73.png)

**Comment by jkbe** [comment]
@zhamanakov Last picture is missing.

**Comment by stursberg** [comment]
@jak-ing thanks! added

**Comment by stursberg** [comment]
![basketball.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ea9589288797ab8ee5b301e81fe086264c22703d46f9692584b37bec407f030a581ca9415e5f44fff08c7ff7b46d76984019af80330b2b9b645bf9fa9015ad00bd2a8a4a84b5be8e4dc2e13f23e18e9d02.png)


![volleyball.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fe9b962f879aab8ee5b301e81fe086264c22703d46f9692584b37bec407f030a581ca9415e5f44fff08c7ff7b46d76984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b5be8e4dc2e13f23e08e9d02.png)

![tischtennis.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fc9d89208a97ac81e7b650e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb27814e80b7bf8848c1eb3c2ce38d8a5d73.png)
![fussball.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46ee8189308082a583abf301b44fff9e2c4533317346f62a20d6b02abb407e560d5a4eaa41585c4df9add829f7b02e6c981e5ab38532022d8c6853beb2901eb70bbb258a4c87b2bd894ec5e83b26f5c6.png)
![othersports.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46e78092269090b980fbab50e611b2843b492d762a10e17132d0e278ec1179050d0a49fe44585944fcfa802ef2e73e218c4e17ff933c0120996048e6edc00db513bb27814e80b7bf8848c1eb3e25e28f8e5d73.png)
![player1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46f8989b3a8791f8cda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8318b500bf21884d81b7bf8948c5ef3f37aa.png)
![player2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46f8989b3a8791fbcda5fd53b652fa912a5265296b51a27b23d6e12cbd472c035a5f48ac415b5641a8a88b7aa0a42062c80d55b98e30063e937f03a6aa8318b500bf21884d81b7bf8945c3e13937aa.png)

**Comment by deeps96** [comment]
TODO:

- [x] Mobile optimized background placement
- [x] Content section 1
- [x] Content section 2
- [x] Content section 3
- [x] Content section 4
- [x] Content section 5

- [x] Make font and image size depend on screen size (application wide?)
- [x] Check mobile section 1
- [x] Check mobile section 2
- [x] Check mobile section 3
- [x] Check mobile section 4
- [x] Check mobile section 5

**Comment by jkbe** [comment]
@deeps96 @jonashering #255 is done and thus the "real" landing page text can be used.

**Comment by jonashering** [comment]
Awesome!

**Comment by jkbe** [comment]
**Reestimation for new sprint: XS (Actual: XS)**

**Comment by stursberg** [comment]
Bullet-points styling:

![Screen Shot 2018-01-24 at 17.22.55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f76b7191a379e80c2953415a4bbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95efe4ae04c51a4113765f43b.png)

**Comment by stursberg** [comment]
please, make default text font-size: 1.2rem (now 1.4 rem)
and for h3 {font-size: 2.2rem;}
(for all pages)

**Comment by jonashering** [comment]
@zhamanakov are these font sizes for mobile and desktop?

DONE
