### ISSUE TITLE
Style footer

### ISSUE THREAD

**Issue by jkbe** [hpi-swt2/sport-portal#186]
Implement footer like shown in #185.

**Estimation: S (Actual: S)**

**Tasks**
- [x] Styling like shown in pictures
- [x] Footer should always stick to the bottom of the page, even if page content doesn't fill the entire page

**Comment by jkbe** [comment]
Footer text background doesn't always need to be white.

**Comment by jak-ing** [comment]
User Story is completed but we wait for #185 to be merged because the branch for #186 is based off the branch for #185 because of certain dependencies.

**Comment by jkbe** [comment]
_Ongoing User Story_

**Reestimation for this Sprint: XS (Actual: S)**

User Story is completed but we wait for #185 to be merged because the branch for #186 is based off the branch for #185 because of certain dependencies.

**Comment by jak-ing** [comment]
Make sure footer doesn't overlap with content on the bottom of page.

**Comment by jkbe** [comment]
Requirements changed:
- [x] Footer should always be visible in front of a white background
- [x] Top margin to content should be at least `~50px`
