### ISSUE TITLE
Create-league/tournament page

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#19]
**AS A** user after login
**I WANT TO** be able to create a new league or tournament
**SO THAT I** start a new sport event

**ACCEPTANCE CRITERIA**

- [x]  by clicking the league button on the "create-event" page a form opens where I can configure the league I want to create
- [x]  In the form I can enter the following things
  - [x] Name (mandatory)
  - [x] Beschreibung
  - [x] choose from league or tournament (mandatory) is pre-selected based on which button was pressed in create event page
  - [x] Sportart (mandatory)
  - [x] Teams oder Einzelsportler -> if nothing is entered both are allowed
  - [x] Maximale Anzahl der teilnehmenden Teams -> if nothing is entered there is no limit
  - [x] Spielsystem (mandatory)
     - [x] if league: "Jeder-gegen-Jeden", "Hin- und Rückrunde " , "Schweizersystem" , "Dänisches System "
     - [x] if tournament: "K.-o. System" , "K.-o. System mit Gruppenphase ", "Double Elimination"
- [x] the form has two buttons
  - [x] create : this creates a league with the given parameters
  - [x] cancel : this cancels the process and brings you back to the create event page
- [x] by creating an league the user is remarked as organizer of this event
- [x] every event gets an unique id(mandatory, automatically assigned)
- [x] if any of the mandatory attributes is missing it is not possible to create the event and the user is prompted to enter them

**Comment by GittiHab** [comment]
Why does the title of this story mention leagues _and_ tournaments but only describes later?

**Comment by MarcelSchmidberger** [comment]
The creation process of leagues and tournaments only differs in a few points and therefore the two forms are basically the same. Therefore it was planned to build both forms for the basic event models in one go. This was intended to enable a different team to work on the tournament stuff later on, without messing with the creation process.

**Comment by MarcelSchmidberger** [comment]
correct Problems stated in #232

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by usame-algan** [comment]
Actual size: M
