### ISSUE TITLE
Configure Matches

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#197]
AS the organizer of an event 
I WANT TO configure how the games are played saying that I want to set the game mode, determine when someone wins and configure how many points the winner, as well as the looser, earns
TO control how each match will be played

ACCEPTANCE CRITERIA
- [ ] When creating and event or when editing an event as an organizer I want to have additional options with already set default values
  - [ ] When I click on the button "Erweiterte Einstellungen" I want to see additional configuration options for all matches
![additional_setting_sportportal](https://user-images.githubusercontent.com/5064619/33808316-9bd51f46-dde4-11e7-9a89-d03f4b9cc335.png)
![image 2017-12-10 20 31 35](https://user-images.githubusercontent.com/5064619/33808562-1f3d4b02-dde9-11e7-9602-229ebef97699.jpg)

      - [ ] When I click on the drop-down menu next to the label "Spielart:   Best of" there are the options 1-8 whereas 1 should be the default. When I hover over the label you can see "(z.B. Fussball = Best-of-1, Tennis = Best-of-3)"
      - [ ] When I click on the drop-down menu next to "Gewinnregel je Spiel" there is one option which says "Sieger ist, wer die meisten Sätze gewinnt"
      - [ ] Next to the label "Punkteverteilung" there are the labels 
          - "Gewinner" and a box in which I can only enter a positive Integer Number (default 3)
          - "Unentschieden" and a box in which I can only enter a positive Integer Number (default 1)
          - "Verlierer" and a box in which I can only enter a positive Integer Number (default 0)

- [ ] When I am in editing mode of an event there is a button "Speichern". When I am in creating an event there stays the Button "Veranstaltung erstellen. When clicking the button it should
            - [ ] store what I just put on the formula or when I didn't put anything on the advanced options store the default values
            - [ ] and set the options for every match in the event (also already created matches)
- [ ] Update the hardcoded points calculation in the match model

**Comment by nikriek** [comment]
Please modify the function after https://github.com/hpi-swt2/sport-portal/pull/292 is merged to reflect the different game modes in the point calculation

**Comment by PoJo93** [comment]
@citron0xa9 I don't see a Field for the Best of:  option

**Comment by citron0xa9** [comment]
@PoJo93 should be fixed now

**Comment by PoJo93** [comment]
@citron0xa9 ok nice. According to the User story there are three points missing

1.   When I click on the drop-down menu next to "Gewinnregel je Spiel" there is one option which says "Sieger ist, wer die meisten Sätze gewinnt"
(Currently Gewinnregel and most sets)

2. "When I hover over the label you can see "(z.B. Fussball = Best-of-1, Tennis = Best-of-3)""

3. If I enter a negative value the error message is in english. Should be german (general criteria)

**Comment by citron0xa9** [comment]
1. Ok, will fix that
2. should be possible, maybe you didn't hover over the correct label? If so maybe the ux is not optimal
3. I can try to change that but could be hard

**Comment by citron0xa9** [comment]
4. add model validation for point limit (currently only in view)
