### ISSUE TITLE
Display match configuration

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#198]
AS a user
I WANT TO see which properties a match has
TO know more details about one match

ACCEPTANCE CRITERIA
 - [ ] There is a label "Gewinner Team " the name of the Winnerteam(when it is determined) " - " Team" and the name of the team
- [ ] Below there is a label "Ort " with the current Place where the event will be played
 - [ ] Below there is a label "Ergebnisse " and then the results of the different matches 
 - [ ] Underneath there is a label "Punkte" which displays the points of the teams below the team names
 
Similar to this one
![screen shot 2017-12-02 at 21 47 06](https://user-images.githubusercontent.com/5064619/33519625-ab511f6e-d7aa-11e7-90d7-bbdb54b746e4.png)
