### ISSUE TITLE
View all events page

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#20]
**AS A** logged in user
**I WANT TO** be able to see a list with all events
**SO THAT** I can get an overview over all events in the system

## ACCEPTANCE CRITERIA
- [x] An "events" button in the menu bar exists 
- [x]  Pressing the button brings the user to a page where all events are listed
- [x] The table shows name, game type (tournament / league), game system and number of participants of the events

**Comment by GittiHab** [comment]
Reviewed and accepted by Product Owner
