### ISSUE TITLE
Create new team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#21]
As User I want to create a team in order to participate in sport events.

**Acceptance criteria:**

- [x] Team has following fields:
	-id(mandatory, automatically assigned)
	-name (mandatory) "Name"
	-description (optional) "Beschreibung"
	-kinds of sports (optional) "Sportarten"
	-private checkbox "Privat"(if private - visible only for team members, by default public - visible for all)

- [x] All fields are anytime editable by all team members.

- [x] Button "Save" ("Speichern") and "Cancel" ("Abbrechen"): visible only in edit modus

- [x] Button "Edit" ("Bearbeiten") : visible only in normal modus

- [x] all buttons are functionable

<img width="552" alt="screen shot 2017-11-11 at 21 09 05" src="https://user-images.githubusercontent.com/27727717/32693088-bf74015a-c724-11e7-8860-bdf2e92e7647.png">

**Comment by bakoe** [comment]
Edit functionality depends on #27: *Roles in team*
