### ISSUE TITLE
Automated filtering in teams table

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#219]
When User opens **table "Teams"**, he sees **IDs** of every team in **wrong** order. Actual behaviour is confusing and should be enhanced.

**Acceptance criteria**

- IDs column should be invisible for user.
- OPTIONAL: Column 'Updated at' should be added as Ruby filters data on it. Alternatively, change filtering on 'Created at' date. 

![image](https://user-images.githubusercontent.com/27727717/33794849-3eab0a4e-dcd4-11e7-8536-1d2a6fc29cdc.png)

**Comment by niconomaa** [comment]
technical tasks
- [x] write view tests to verify absence of id col
- [x] write tests to verify order of teams by creation date
- [x] modify view such that it does not show id col
- [x] modify controller to change ordering of teams by creation date
    - [this](https://stackoverflow.com/questions/4055799/how-do-you-order-by-a-custom-model-method-that-has-no-attribute-in-sql) might give a hint
