### ISSUE TITLE
Min/Max Players in Teams

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#221]
**AS AN** organiser of an event
**I WANT TO** be able to specify the minimum and maximum number of players required in a team to join an event
**SO THAT** only teams which fulfill this requirement can join the event

## ACCEPTANCE CRITERIA
In the form for creating/editing an event if the "Team" option is selected:
- [x] there should be an number field labeled "Minimum players per team"
- [x] there should be an number field labeled "Maximum players per team"
- [x] the value of the minimum field is not allowed to be greater than the maximum field
- [x] if a user wants to join an event with his team where the organiser specified the maximum field only teams with less than the specified number of members are allowed to join
- [x] if a user wants to join an event with his team where the organiser specified the minimum field only teams with more than the specified number of members are allowed to join

**Comment by GittiHab** [comment]
This also occurs in #104

**Comment by ConstantinLange** [comment]
@GittiHab I discussed this problem relative to #104 with Fabian Pottbäcker. It was a missconception of their PO. They don't work on this.

**Comment by GittiHab** [comment]
Why must the lower limit be >1? I want to be able to only have one person in there.

**Comment by GittiHab** [comment]
If I edit the members in a team (add/remove) and this contradicts to the min/max constraints then I should not be able to do the respective edit action (e.g.: can't remove player, if a team that is part of an event where it fulfills the lower limit of members)

**Comment by fswt** [comment]
Min/Max players field should be directly under Team/Single selection field.

**Comment by GittiHab** [comment]
The minimum and maximum value is displayed incorrectly in the form. Example: I create a team event and set the maximum team size to 5. If I added the same event the maximum team size is displayed as 1. If I want to join with a team of 5 people it works though.
