### ISSUE TITLE
Remove "Players" page

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#223]
**AS AN** administrator
**I WANT TO** be the only one to see the page with all users
**SO THAT** users not participating in an event can be anonymous on the system and all others have a more sleek interface

## ACCEPTANCE CRITERIA
- [x] If a user is not the admin, there is no link to "Players" in the navigation bar
- [x] If I am not an administrator I cannot access the page where I can see all players
- [x] It should still be possible to view the profile page of one specific user for all logged in users

**Comment by GittiHab** [comment]
Looks good
