### ISSUE TITLE
Calculate playing schedule after the registration deadline

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#231]
As joined player or organizer of a league
I want to see playing schedule with all joined players
So that I know who will play with whom

**Acceptance Criteria**

- [ ] The playing schedule is only after the registration deadline visible
- [ ] The playing schedule contains all joined players
- [ ] The playing schedule button on the event page should either have no effect or be invisible until after the deadline (choose whatever ist easier)

**Comment by MarcelSchmidberger** [comment]
could this be done for the tournament as well? And could you hide the "Übersicht" Button too?

**Comment by Askir** [comment]
Yes should be quite easy to implement.
