### ISSUE TITLE
Correct phrases in the create league form

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#232]
As an league organizer
I want a consistent register in the form
In order to not to get confused

**Acceptance Criteria**

- [ ] All  phrases in the create league form need to be German.

- [ ] "Solo / team" should be "Einzel-/ Teamsport" to be consistent with the dropdown menu

- [ ]  correct spelling mistake "Dauer in tagen" in form as well

**Comment by MarcelSchmidberger** [comment]
@usame-algan könntest du eventuell noch "Anzahl Teams" in "Anzahl der Teams" umbenennen, dann ist es wenigstens grammatikalisch korrekt. Mir ist leider keine bessere Bezeichnung eingefallen, "Teamanzahl" klingt auch komisch, oder? Hast du noch eine Idee?

**Comment by usame-algan** [comment]
@MarcelSchmidberger Anzahl Teams können aber auch Einzelspieler sein oder? Wäre dann nicht Anzahl der Teilnehmer oder Teilnehmeranzahl passender? Um den Aufwand gering zu halten würde ich diese Änderung in meinem aktuellen PR #210 mit rein nehmen und dieses issue referenzieren.

**Comment by MarcelSchmidberger** [comment]
ja, "Teilnehmeranzahl" ist besser1

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by usame-algan** [comment]
Actual size: S
