### ISSUE TITLE
End of an event

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#233]
As Organizer of an event,
I want to be able to end an event
In order to conclude an event.

An event ends when the event organizer manually defines it to be finished.

**Acceptance Criteria**

- [ ] only organizer and the admin see an end event button on the event page

- [ ] when an event is finished it enters archive mode, and therefore will no longer be editable (no matches and the entire event)

- [ ] an archived Event should be labled so

- [ ] it displays the top 3 placed participants

- [ ] organizer should be able to end an event prematurely to "cancel" it. The event still will enter archive mode and the top placed positions will be the winners (ask tournament team for handling of tournaments)

- [ ] check whether it would be easy to enable an reactivation from archive mode by the organizer/admin. If you think so please ask me again for further instructions.
