### ISSUE TITLE
Confirm a game result

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#236]
AS a participant of a match
I WANT TO store the result of the match and let it be confirmed by a participant of the other team
TO make sure that nobody enters false results

ACCEPTANCE CRITERIA
- [x] Only when I am a participant (nobody else) of a match I want to be able to store the results of the match. ( I have this option when I see the "Spielplan" and click on Bearbeiten of a Match See #198 ) 
    - [x] When the participant of the first team entered a result for the match and saved it has to be confirmed by someone from the other team (one checkmark should appear behind the results)
         - [x] Only when I am a participant in the other team (nobody else) I will see added to the button "Speichern" a button "Bestätigen"
             - [x] When I click the Button "Bestätigen" the system should store that the result of the match is now valid and show this in a visual representation of showing two checkmarks behind the result (the button Bestätigen vanishes)

This is a way of how the screen could change
![image 2017-12-10 21 29 47](https://user-images.githubusercontent.com/5064619/33809091-3ffd1cc0-ddf1-11e7-87fe-46e492920739.jpg)

**Comment by PoJo93** [comment]
Es ist noch ein Bug drin @nikriek 

Wenn ich ein Ergebnis eintrage und der andere es bestätigt und ich dann nochmal auf bearbeiten gehe ohne etwas zu ändern wird der Status auf nicht bestätigt gesetzt was ja kein Sinn macht wenn ich das Ergebnis nicht änder. Könntest du das noch fixen?

Werden jetzt die Punkte so oder so mit reingezählt in den Score? Oder nur wenn ein Ergebnis bestätigt wurde

**Comment by nikriek** [comment]
Sure, let me fix that. For simplicity the results are used in the final score. Changing that or indicating non confirmed results for matches should be defined in another ticket I think.
