### ISSUE TITLE
Delete team member

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#24]
As Team Owner I can delete other team members.
	
Acceptance criteria:

- [x] Only Team Owner can delete other team members

- [x] Team Owner can't delete himself if there are no other team owners in team

- [x] Team Member can delete himself

**Comment by bakoe** [comment]
depends on #27: *Roles in team*

**Comment by niconomaa** [comment]
actual time: 15

**Comment by niconomaa** [comment]
### technical requirements for this issue:
> Only Team Owner can delete other team members
- add functionality to `Ability` that checks whether the executing user is a team's owner
- authorize corresponding `TeamsController` action to use `Ability` and allow action based on user's privileges
> Team Owner can't delete himself if there are no other team owners in team
- add functionality to `Ability` to prevent deleting all owners
>  Team Member can delete himself
- add check in`Ability` that allow members to delete themselves
