### ISSUE TITLE
Teams Table shows number of members instead of IDs

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#247]
Teams Table shows the number of team members. Numbers are assigned according to logical order (enumeration of members).

Actual behaviour

- Table has ID column

- User sees IDs of team members in ID column

Correct behaviour

- Table has "Nummer" column instead of ID column
- Team members are enumerated to see the number of players in a team

![screen_shot_2017-12-12_at_10_29_05](https://user-images.githubusercontent.com/27727717/33880907-6cc6dcd0-df33-11e7-8e02-a1b07069fe9e.png)

**Comment by niconomaa** [comment]
- [x] write view tests to verify absence of id column and presence of number column as well as controller tests to check correct ordering
- [x] ensure consistent ordering of returned players in controller
-  [x] modify view such that in contains the number of each player in the correct column
    - [this](https://stackoverflow.com/questions/3098060/created-a-numbered-list-with-for-loop7) might be a clue
