### ISSUE TITLE
Assign/delete team ownership

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#25]
As Team Owner I can assign or delete team owner rights to other team members.

**Acceptance criteria:**

- [x] Only Team Owner can assign rights to other team members

- [x] Only Team Owner can delete rights of other team members

- [x] Team Owner can delete his own rights, if he is not the only one Team Owner

- [x]  Assign/delete rights button is visible only for Team Owners, buttons switch each other (if user is team owner -> delete rights, if not  -> assign rights)

**Comment by bakoe** [comment]
depends on #27: *Roles in team*

**Comment by lheilmann** [comment]
@jonasnoki @tomkellog Boys let's have a chat before you start implementing this feature! I started implementing a first approach of assigning a team ownership/membership to a user, because a criteria in #27 is colliding with some criterias of this issue. See progress in #27.

**Comment by bakoe** [comment]
@jonasnoki @tomkellog Please also see [my comment in #27](https://github.com/hpi-swt2/sport-portal/issues/27#issuecomment-345540842) regarding the usage of the [cancancan gem](https://github.com/CanCanCommunity/cancancan) for defining abilities – could be useful for this user story.

**Comment by niconomaa** [comment]
actual time: 15

**Comment by niconomaa** [comment]
#### technical requirements for this issue

> Only Team Owner can assign/ delete rights to other team members
- check in `Ability` whether acting user is team's owner
> Team Owner can delete his own rights, if he is not the only one Team Owner
- check in `Ability` whether actions user is only remaining team owner when trying to perform action on himself
>  Assign/delete rights button is visible only for Team Owners, buttons switch each other (if user is team owner -> delete rights, if not -> assign rights)
- perform checks for all actions in view
