### ISSUE TITLE
Team Logo

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#252]
As User I want to place **logo** of my team to the **team page** to differentiate from other teams.

**Acceptance Criteria**

- There is a button "Upload logo" on the team page
- Each team member can upload a picture
- Picture can be changed or deleted anytime
- The picture should not be larger than 300 KB
- The picture should be resized to squared form 350 x 350 

**NOTE**
Check existing solution #39

**Comment by conradlempert** [comment]
**Development Tasks**

- [x] Add avatar to team model
- [x] Add upload segment to form view
- [x] Show avatar on team page
- [x] Make picture resolution 350x350
- [x] Allow only team members to change picture with cancancan
- [x] Test Coverage 99.9%

**Comment by lheilmann** [comment]
@svitlanakalancha Please see #252 and talk to @conradlempert about defining the acceptance criteria resizing images.

**Comment by svitlanakalancha** [comment]
we have agreed on it with @conradlempert
