### ISSUE TITLE
Invite users to team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#26]
As team member I can invite other users in order to expand my team.

**Acceptance criteria:**

- [x] The invited user must have an account on the platform
- [x] Button to send an invitation (see mockup)
- [x] Each team member can invite player to the team
- [x] Team member put an email of person and click "Neuen Spieler einladen" button
- [x] Email is validated automatically, if the user with such account exists, he/she can be added to the team
- [x] The invited person is automatically added to the team after being invited and is shown in the table
- [x]  If the person is already in the team, he/she can't be added twice

<img width="674" alt="screen shot 2017-11-25 at 08 19 14" src="https://user-images.githubusercontent.com/27727717/33228355-5e75b548-d1b9-11e7-818c-e9cf67d74b18.png">

**Comment by bakoe** [comment]
depends on #27: *Roles in team*

**Comment by bakoe** [comment]
**Development tasks**

- [x] Add a `post :assign_membership_by_email` routing to the `routes.rb`
  - test the route in `teams_routing_spec.rb`
- [x] Add a `:assign_membership_by_email` method to the `teams_controller.rb`
  - Algorithm: 
    - check whether a user with the specified email exists
      - if there is a user: 
    check whether he/she is already a member of the team
          - if he/she is not a member yet: 
    add the user to the team's members
    **and** trigger a notification email to the user invited[1]
    **and** redirect to the team page
          -  if he/she is a member already:
    do nothing (e. g. redirect to the team page)
    **and** maybe show a message like "the user is already a team member" (localized!) 
      - if there is no user with the specified email:
    do nothing (e. g. redirect to the team page)
    **and** maybe show a message like "there is no user with the specified email" (localized!) 
  - test the method in `teams_controller_spec.rb`
- [x] Add an ability for `:assign_membership` to `ability.rb`
  - that allows only team members (includes owners) and admins (only if necessary – admins usually can do everything all the time „automatically“ already via `can :manage, :all`) to do this action
  - test the ability in `ability_spec.rb`
- [x] Add an (initially hidden) [bootstrap modal](https://v4-alpha.getbootstrap.com/components/modal/#examples) to `teams/show.html.erb`
  - that is only rendered to HTML when the user is able (CanCanCan) to `:assign_membership`
  - with the elements from the following mockup:
    <img width="209" alt="bildschirmfoto 2017-12-02 um 13 35 22" src="https://user-images.githubusercontent.com/807665/33515572-ac95fcc2-d765-11e7-9030-5fd5d3a1a225.png">
  - with localized strings
  - **without** autocompletion of email addresses
  - that sends a POST request to the `assign_membership_by_email` route (no AJAX yet – simply send the POST request via a form)
  - test the rendering in `teams/show.html.erb_spec.rb`
  - test the functionality in `teams/show.html.erb_spec.rb`
- [x] Add a button to `teams/show.html.erb`
  - that opens the modal on click (via JavaScript – see [bootstrap modal](https://v4-alpha.getbootstrap.com/components/modal/#examples) manual)
  - that is only rendered to HTML when the user is able (CanCanCan) to `:assign_membership` (team members, team owners and admins)
  - test the rendering in `teams/show.html.erb_spec.rb`
  - test the functionality in `teams/show.html.erb_spec.rb`
- [ ] Additional important tests:
  - Test that users that are neither members nor owners of a team **cannot** assign memberships by mail (neither via the UI nor via a manual POST request)

[1] Since @MerlindlH's team has not yet implemented custom emails but only overridden devise notification emails (see #174), we could either implement custom emails by our own (see [Rails: Action Mailer Basics](http://guides.rubyonrails.org/action_mailer_basics.html) or co-ordinate with their team whether they can share any code (snippets) with us.

**Comment by birneamstiel** [comment]
@bakoe thanks for listing the tasks, sounds reasonable to me! We might want to try keeping the controller as slim as we can by externalizing some of the checks you listed under "Algorithm" (implement as validation, maybe?).

**Comment by bakoe** [comment]
Actual time I invested in this issue: 3 h
