### ISSUE TITLE
Results of ranking lists

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#272]
**AS A** participant of a ranking list event
**I WANT TO** be able to add matches to ranking lists
**SO THAT** the score can be displayed

## ACCEPTANCE CRITERIA
- [x] On the detailed page of a ranking list event there should be a button "Add match" next to each participant in the participants/ranking list if the logged in user is a participant him-/herself.
- [x] When clicking the button the user should be shown a form where he can specify the result of the match against the other player (next to whom the button was)
- [x] When the user saves the form the match should be saved and both users score (the user who added the match and the opponent) should be updated according to the metric of the ranking list

**Comment by GittiHab** [comment]
This user story needs feedback: Should the opponent be able to verify the result first, how does this fit in to the existing match-event system?

**Comment by GittiHab** [comment]
This story is linked to #135

**Comment by GittiHab** [comment]
I updated the acceptance criteria according to the discussion with @Jeilef.

**Comment by GittiHab** [comment]
Looks good
