### ISSUE TITLE
Visibility in team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#28]
As User I can see the information about other teams.

Acceptance criteria:

- [x] all teams are by default public

- [x] nobody can see info about team except team members, event owner and admin, if team is private

- [x] private teams are not visible on the page with all teams 

- [x] pages of private teams are not accessible for not team members

**Comment by bakoe** [comment]
depends on #27: *Roles in team*

**Comment by bakoe** [comment]
Distinction between private and public teams depends on #21: *Create new team*

**Comment by bakoe** [comment]
# Current status

## ☑️ Done:
- Added tests for the read abilities of logged-out and logged-in users (depending on whether they are team members/owners or not)
- Extended `ability.rb` to fulfill the requirements regarding the team reading permissions of logged-out and logged-in users
- Did successful manual acceptance tests to verify the abilities' influence on the teams' index and show views (logged-out, logged-in and logged-in as an owner/member of a private team)

## 📋 To Do:
- [ ] ~~Extend the abilities test for the read abilities of admin users (see #46)~~
- [ ] ~~Handle user's admin status in the `ability.rb` _model_ file (see #46)~~
- [x] Either comment in or delete the `create` and `update` abilities for logged-in users (see #21)
- [x] Either comment in or delete the `destroy` ability for logged-in users (see #22)
- [x] Either comment in or delete the `assign_ownership_to` and `assign_membership_to` abilities for logged-in users (see #24, #25)
- [x] **Make sure the existing tests for the teams controller don't fail anymore** (see #27)

## ⚠️ Needs clarification:
- Do we already make sure that teams “are by default public” (maybe via #21)? If not, how and where do we want to implement this functionality?
- Which issue/story is responsible for adding abilities for admin users? (it is already included in here: https://github.com/hpi-swt2/sport-portal/issues/46)

**Comment by bakoe** [comment]
Regarding the first acceptance criteria (“all teams are by default public”): #28 made sure that all newly created teams are by default public. To ensure that already existing teams without a private/public property are also public, we could think about adding a database migration that assigns every team that is neither public nor private the “private: false“ property.

**Comment by bakoe** [comment]
Regarding the second acceptance criteria (“nobody can see info about team except team members, event owner and **admin**, if team is private”): #46 introduces the admin role. We’ll try to make sure that #46 gives the admin(s) the ability to read (as well as create, update and destroy) every team, regardless of whether it is public or private.

**Comment by birneamstiel** [comment]
Estimated time: 13h
Actual time: 9h
