### ISSUE TITLE
Join event as team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#29]
**AS A** team owner
**I WANT TO** be able to join team events
**SO THAT** my team can participate in events

## ACCEPTANCE CRITERIA
Based on #85 
- [x] On the _all events_ page **and** detailed page of the event, if an event is a team sport there should be a button "join" as long as the user is not in a team participating at the event
- [x] If the user clicks join, an overlay should appear asking the user to select the team he would like to participate with
- [x] Only teams the user is an **owner** of and which are valid for this event (according to the options of the event) should be displayed
- [x] If the user is in no (valid) team there should be a message telling the user about this and offering to create a new team
- After the team has joined the event
  - [x] The button should change to "leave event"
  - [x] The "leave event" button should be greyed out (disabled) to all team members except the owners
  - [x] When the "leave event" button has been clicked and it was enabled the team should leave the event and it should not be labeled "Participating" anymore
  - [x] The team should have joined the event
  - [x] The event should be labeled with "Participating"
- [x] Every time the users open the _all events_ page all events, where a team they are in has joined, should be labeled with "Participating"
- [x] The "join" button is only visible as long as the deadline has not passed
- [x] Only logged in users can join events

**Comment by bakoe** [comment]
depends on #49: *create Model for events*

**Comment by bakoe** [comment]
depends on #27: *Roles in team*

**Comment by GittiHab** [comment]
Mockups to this user story  
If the user wants to join a team event he needs to pick a team he wants to join with. Only teams he is owner of and which fulfill the event requirements are shown to him.
![join_as_team_1](https://user-images.githubusercontent.com/6453623/33240363-361ce326-d2b5-11e7-8132-f95f7845860d.jpg)
If the user is not an owner of any team, he gets a message explaining to him and offering to create an own team.
![join_as_team_2](https://user-images.githubusercontent.com/6453623/33240364-363d1416-d2b5-11e7-9f3d-a215464f78e2.jpg)

**Comment by stlutz** [comment]
Todo list:
- [ ] fix error `ParameterMissing in EventsController#join`
- [ ] refactor routes
- [ ] change from users to single player teams
- [ ] test ui interactions
- [ ] rework cancancan authorizations

**Comment by GittiHab** [comment]
There seems to be a bug with joining, see #270. Please try to have it working with this user story.

**Comment by GittiHab** [comment]
There are **following issues**
- [ ] Bug #270 still exists
- [ ] If I join as a single player I don't want a new team to be created in the teams list (see image)
- [ ] There is **no** join button for team events – therefore the 1. acceptance criteria is not fulfilled and all others cannot be tested.

**Comment by GittiHab** [comment]
New teams for single player events are created:  
<img width="1204" alt="screen shot 2018-01-13 at 11 38 08" src="https://user-images.githubusercontent.com/6453623/34905341-f66aecc4-f856-11e7-9d8b-0b4bd0c2762f.png">

There is **no** join button for team events:  
<img width="1055" alt="screen shot 2018-01-13 at 11 43 14" src="https://user-images.githubusercontent.com/6453623/34905342-f68a4e48-f856-11e7-9614-0d5de37b7a23.png">

**Comment by GittiHab** [comment]
Looks great :)
