### ISSUE TITLE
[deprecated]Add predicted end date of event to event creation form

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#297]
is deprecated and now included in #296 

As organizer/Participant of an event
I Want to know an estimated end date of the event
In order to plan/schedule my participation (determine whether I can participate during the whole event etc.)

**Acceptance Criteria**

- [ ] there should be an field expected end date"erwartetes Enddatum" below the start date and gameday length selection
- [ ] this end date should update itself depending on start date and game day length
- [ ] the end date should be calculated using the max team count and the game system and update on changes of them
- [ ] it should also be shown on the event page and update on changes of the event configuration by the organizer
