### ISSUE TITLE
Event live cycle

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#298]
This is an summary of all event processes
An Event follows following live cycle:

![image](https://user-images.githubusercontent.com/29160369/34655418-a6e1534c-f409-11e7-9f13-5ffea5bc90d8.png)

Please ensure that following requirements are met:

**Event creation**
- [ ] select event type(league/ tournament) then configure event #227
- [ ] create new event: #18, #19, #232, #297 , #296, #279  (league), #105(tournament)
- [ ] Min/Max Players for Teams #221
- [ ] game systems #141, #143, #139 
- [ ] Configure Matches #197
- [ ] event gets an event page: #31/#32

**Joining phase**
- [ ] You can only join before the joining deadline  #53
- [ ] The joining process is specified in #85 (single player) and #29 (team)

**running phase**

- [ ] After the joining phase enden the playing schedule is calculated and will be visable
 #35, #144, #105, #145 #231 , with joined players#128 or teams #140 and game results can be added #36
- [ ] technically the event has not started yet (start defined by start date) but there seems to be no reason to add another state
- [ ] there are no restrictions to entering match results
- [ ] organizer no longer should be able to edit following event parameters: (Spielsystem, Anzahl Teams, Einzelspieler/ Teams, startdate)
- [ ] if game day length is changed at date X all following playing days (starting from X) should be adjusted

**event end**

- [ ]  End of an event is described in #233

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.
