### ISSUE TITLE
Event Templates

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#299]
As event organizer
I want to create common events with no configuration effort
So that I can create an event quick an easy

**Acceptance Criteria**

- [ ] Tiles for common events (see #294) should be displayed on the create event page
- [ ] there should be a create button for each tile wich will create an new event with this specification
- [ ] contact your PO for specific event configurations

**Comment by MarcelSchmidberger** [comment]
Event templates |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |   |   |   |   |   |  
Ligen |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |  
Name | Bild | Beschreibung | Teilnehmerzahl | Sportart | Anmeldefrist | Begin | Ende | Teilnahmeform | Auswahlverfahren | Spielsystem | Spieltagdauer
Tischkickerliga | 1 | In dieser mitreißenden Tischkickerliga tritts du gegen deine Freunde und   Kollegen an und der beste Spieler wird in epischen Duellen ermittelt. Trete   jetzt bei, um teil dieses unvergesslichen Erlebnisses zu sein! | 12 | Tischkicker | Tag des Erstellens des Events  + 1   Woche | Tag des Erstellens des Evnets + 2 Wochen | wird aus spieltaglänge + startdatum berechnet (wird gerade von tobi   implementiert) | Einzelteilnahme | first come first serve | jeder gegen jeden | 7 Tage
Fußballliga | 2 |   | 16 | Fußball | Tag des Erstellens des Events  + 1   Woche | Tag des Erstellens des Events  + 2   Woche | wird aus spieltaglänge + startdatum berechnet (wird gerade von tobi   implementiert) | Teamteilnahme | first come first serve | Hin und Rückrunde | 7 Tage
  |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |  
Turnier |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |  
Name | Bild | Beschreibung | Teilnehmerzahl | Sportart | Anmeldefrist | Begin | Ende | Teilnahmeform | Auswahlverfahren | Spielsystem |  
Volleyball Turnier | 3 | Sonne, Sand und jede Menge Spaß, das diesjährige Volleyball Turnier lässt   keine Wünsche offen. Meldet euch jetzt an! | 8 | Beachvolleyball | Tag des Erstellens des Events  + 1   Woche | Tag des Erstellens des Events  + 2   Woche | Tag des Erstellens des Events  + 6   Wochen | Teamteilnahme | first come first serve | KO-System |  
Tischtennistturnier | 4 |   | 16 | Tischtennis | Tag des Erstellens des Events  + 1   Woche | Tag des Erstellens des Events  + 2   Woche | Tag des Erstellens des Events  + 6   Wochen | Einzelteilnahme | first come first serve | KO-System |  
  |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |  
Ranglisten |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |  
Name | Bild | Beschreibung | Teilnehmerzahl | Sportart Spielsystem | Anfangswert |   |   |   |   |  
Schachrangliste | 5 |   | 100 | Schach | 20 |   |   |   |   |   |  
Tischkickerrangliste | 6 |   | unbegrenzt | Tischkicker | 20 |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |

**Comment by MarcelSchmidberger** [comment]
it would be nice if the templates would be aligned with the corresponding events
![image](https://user-images.githubusercontent.com/29160369/35812148-818c456e-0a90-11e8-9064-e5b3076dd4f8.png)

so they should be 3x2 in dimensions, just like this:
![image](https://user-images.githubusercontent.com/29160369/35812201-a3a02a26-0a90-11e8-9f5a-8b42e4ccff31.png)
