### ISSUE TITLE
Join existing team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#30]
As User I can ask to join any team to take part in some event.
	
**Acceptance criteria:**

- [ ] User can join only public teams
- [ ] There is a button "Team beitreten" on the team page (see #381)
- [ ] When user clicks the button on some team page, team owner(s) receives an automatically generated email
- [ ] Team owner can approve or decline the application by clicking correspondent links in the email. Alternatively team owner can approve or decline an application on the website (?)
- [ ] Email includes link to the profile of applicant

**Comment by bakoe** [comment]
depends on #27: *Roles in team*
