### ISSUE TITLE
Notifications: team

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#307]
As User I want to be informed about changes in my teams to be better prepared for coming sports events.

**Acceptance criteria**

- general requirements see in the #301 
- emails are automatically generated when triggered
- the text of emails is predefined and includes placeholders for customization (see texts below)

Triggers are:

- User is added to a team and receives correspondent email.

> Hallo _user name_,
> Du bist dem Team _team name_ beigetreten.
> ODER Deine Teamliste wurde aktualisiert.
> Viel Erfolg beim Sport!
> Platform name team

- Team where user participates was registered to some event

> Hallo _user name_,
> Dein Team _team name_ nimmt jetzt an dem Event _link_ teil.
> Viel Erfolg beim Spielen!
> Platform name team

**Important**
Check issues #57 and #149 and communicate with other dev teams

**Comment by bakoe** [comment]
## Clarification needed

- [X] @svitlanakalancha: Should the “Team where user participates was registered to some event” notification be controlled by the user's “Team notifications” or by his/her “Event notifications”? 
  - --> stays at “Team notifications”

## Development Tasks

- [x] Create a `TeamMailer` inheriting from `ApplicationMailer` via the corresponding rails CLI command
- [x] Add `user_added_to_team` method to `TeamMailer` that prepares emails following the template from the corresponding AC
  - Bonus: Send the mail not to `hans@example.org` but to `Hans Mustermann <hans@example.org>` – see http://guides.rubyonrails.org/action_mailer_basics.html#sending-email-with-name
- [x] Add private `prevent_delivery_to_unsubscribed_users` method to `TeamMailer` model that checks the user's `team_notifications_enabled` (see #301) flag and disables the delivery when flag is set to false – see http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-callbacks
- [x] Add `after_action` hook to `TeamMailer` model which triggers the `prevent_delivery_to_unsubscribed_users` method
- [x] Add `team_registered_to_event` method to `TeamMailer` model that prepares emails following the template from the corresponding AC
  - Make sure that the link URL is generated correctly – see http://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views
  - Bonus: Send the mail not to `hans@example.org` but to `Hans Mustermann <hans@example.org>` – see http://guides.rubyonrails.org/action_mailer_basics.html#sending-email-with-name
- [x] Add `send_mail_when_created` method to `TeamUser` model that delivers the corresponding `(Team)Mailer` mail (`user_added_to_team`) method when called.
- [x] Add `after_create` hook to `TeamUser` model which triggers the `send_mail_when_created` method
- [x] Add `send_mails_when_adding_team` method to `Event` model that delivers the corresponding `TeamMailer` mail (`team_registered_to_event `) method when called.
- [x] Trigger `send_mails_when_adding_team` at the end of `Event` model's `add_team` method

- [x] Don't forget corresponding tests
- [x] Make sure that localizations are used

**Comment by lheilmann** [comment]
@svitlanakalancha Have you thought about links in the email text/html? For instance, in your first described scenario the team name could be a link pointing to the teams show page? In scenario one could insert links to teams show page and event show page.

**Comment by lheilmann** [comment]
@svitlanakalancha I have just seen, that @bakoe has already implemented a link pointing to the event show page in the second scenario. :+1: What about having a link to team show page in both scenarios, too?

**Comment by bakoe** [comment]
Bugs noticed after deploying the feature to Heroku:

- [ ] When a user creates a new team, a new `TeamUser` instance is automatically created for him. This causes a “You have been added to team …” e-mail to be sent which is nonsense in this context
- [ ] When a single user joins an event, a “fake team” is created automatically, which also creates a new `TeamUser` instance. This leads to the sending of two e-mails: One for “You have been added to team …” (which is quite nonsense) and one for “your team … has joined the event …” (which is also rather nonsense regarding there is no real team which joined an event).
… This may need further clarification about how single-player “fake teams” should be handled regarding the e-mail notifications

**Comment by bakoe** [comment]
Actual time I invested in this issue: 6 h
