### ISSUE TITLE
event page as user

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#31]
**AS A** logged in user
**I WANT TO** visit the event page 
**SO THAT** I can check out the event details

**ACCEPTANCE CRITERIA**

- [x] the users can view a detailed event page for every event they have access to
- [x] the event page displays
  - [x] event name
  - [x] description
  - [x] whether it is a league or tournament
  - [x] which kind of sports it is
  - [x] teams or single player
  - [x] maximum amount of player/teams who can participate 
  - [x] game system

**Comment by stlutz** [comment]
At the moment all users have access to all events. Who is responsible for managing user permissions?

**Comment by MarcelSchmidberger** [comment]
Later on the event creator/organizer will be able to adjust the visibility of an event. For example he might be able to choose from **open** (everybody even without login can visit the event page), **public** (login needed to view the event page) of **private** (only viewable after invite)(Disclaimer: these labels are still in working progress). So in a nutshell in the future the organizer is supposed to be able to manage access permissions.

**Comment by stlutz** [comment]
For now, can we consider this issue complete then? Because implementing event visibilities seems like a whole new user story to me.

**Comment by MarcelSchmidberger** [comment]
Yes, your right. Your issue is completed and visibility will be handled in an upcoming user story

**Comment by GittiHab** [comment]
Reviewed and accepted by (the responsible) Product Owner
