### ISSUE TITLE
event page as organizer

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#32]
**AS A** organiser of an event
**I WANT TO** be able to edit the settings of events I created when viewing their page
**SO THAT** I can change the settings of my events

**ACCEPTANCE CRITERIA**

- [x] organiser can visit the event page
- [x] on the top right there is an edit button
- [x] pressing the icon makes all fields editable
- [x] on the bottom of the page a *save* and *cancel* button appears if the organizer is in edit mode
- [x] if something was changed and the organiser saves the changes by pressing the *save* button the changes are saved and the organiser leaves the edit mode for the page
- [x] pressing the cancel button will drop any changes and also leave edit mode
- [x] only the organiser of an event is able to edit the respective event
