### ISSUE TITLE
Sporttype field in event creation as dropdown

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#324]
As an event organizer
I want the sporttype field in the event creation to be a dropdown menu
In order to allow for easier filtering of the all events page later on.

This will unify spelling and representation of different sporttypes.

**Acceptance Criteria**

- [ ] The dropdown should contain:

- Fußball
- Basketball
- Volleyball
- Tennis
- Tischtennis
- Tischkicker
- Andere
(there may come more)
- [ ]  The results should be shown in alphabetical order (Exception: Andere should be the last element(if not to complicated))
- [ ] The selection should be shown correctly on the event page and the all events list
- [ ] automatic focus after textinput would be nice (ask if unclear)

**Comment by MarcelSchmidberger** [comment]
the general idea of the last point is to have an dropdown where you can use keyboardinput to do the selection similar to what amazon does.

![image](https://user-images.githubusercontent.com/29160369/35046436-49a3a500-fb97-11e7-84a0-d497d2b227bd.png)

Here you can start typing and the right result is highlightet. But I have no idea how complicated something like this would be to implement. If you are uncertain about it dont do it.
