### ISSUE TITLE
Upper limit participants in an event

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#325]
Entering a too large number (like 1000000000000000000000000)in the "Anzahl Teams" Field will result in a crash of the creation process.

**Acceptance Criteria**

- [ ] The maximal upper limit of the Team count should be 1000 Teams for an Event.
- [ ] If a User enters a Number larger than 1000 they should be notified that the entered Number was to o large and needs to smaller than or equal to 1000.
- [ ] Should be ensured after editing an event as well
- [ ]  check whether leaving the field empty (player count "unbegrenzt") result in any problems, if yes make it an mandatory field

**Comment by usame-algan** [comment]
Actual size: XS
