### ISSUE TITLE
Remove option to delete matches

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#329]
**AS** a user or organizer (not as an admin)
**I WANT TO** not be able to remove a match with a button
**TO** ensure that the event is not deleted and the playing schedule stays intact

**ACCEPTANCE CRITERIA**
- [x] There is no delete button for a match in the playing schedule
- [x] When I click on the match to see or edit its properties I also have no option to delete the match
- [x] In the case that a match is deleted for another reason it should not be the case that it deletes the whole event
