### ISSUE TITLE
Calendar settings for events

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#33]
**AS AN** organiser of an event
**I WANT TO** I want to select a start date, and a finish date when creating an event
**SO THAT** the users know when an event will start and end

## ACCEPTANCE CRITERIA

- [x] you can enter a start date of an event
- [x] you can enter a duration or a finish date
- [x] the selection of the dates should be possible either by entering the numbers, or by selecting them from a calendar view similar to [https://www.bahn.de/p/view/index.shtml](url)

**Comment by GittiHab** [comment]
Following things should be improved:

- [x] If I click on a date in the calendar, the calendar should be hidden and the date is added into the text box.
- [x] It is probably best if we remove the duration field.

**Comment by GittiHab** [comment]
There is in fact a small bug: If I set the date, then the duration is automatically filled in. If I then change the duration but immediately after click on the end date and then somewhere else, the duration and dates are inconsistent.
