### ISSUE TITLE
Players should only be able to edit the matches in which they played

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#332]
**AS** player of a match, organizer of an event(or admin) and no one else
**I WANT TO** be able to edit the scores of the matches in which I played in
**TO** ensure that no foreign users edit them 

**ACCEPTANCE CRITERIA**
- [x] When I am not an eligible person( see top) I don't have the option to edit or enter scores for a match
   - [x] When I see the playing schedule of a event I don't see a button to submit a new score nor do I see the textboxes to enter values
  - [x] When I go in the settings of a match I am just able to see the scores entered for a team but not able to suggest new ones or edit the current ones
  - [x] I can just see the entered scores and their status (confirmed by both teams or just suggested by one team)
- [x] When I am a eligible person I have the already provided functionality of editing scores
