### ISSUE TITLE
Display Organizer on event page

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#344]
As a Participant
I want to know who is the organizer of the event
So That I can contact him if necessary

**Acceptance Criteria**

- [x] There should be an field with the organizers name 
- [x] It should be displayed in all event types
- [x] the name needs to clickable and lead to the organizers profile page

**Mockup**

![image](https://user-images.githubusercontent.com/29160369/34922598-56282e74-f992-11e7-8369-fbd9bbd26d0e.png)
