### ISSUE TITLE
editing constraints for events

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#346]
As participant / Organizer
I dont want an event to change completely after it started
In order to prevent confusion due to changes

**Acceptance Criteria**

- [ ]  Teilnehmerzahl, Anmeldefrist, Startdatum, Teilnahmeform und Spielsystem (and Anfangswert for ranking lists) should not be changeable after event start
- [ ] Name, Beschreibung, Enddatum, Spieltaglänge can be changed later on
- [ ] admin may change everything

**Comment by MarcelSchmidberger** [comment]
no change of team and singel player
max zahl constraints

**Comment by MarcelSchmidberger** [comment]
when changing the join limit  date of an event where matches have already been entered I get this error:
![image](https://user-images.githubusercontent.com/29160369/35783382-50c375ae-0a06-11e8-93d0-b9c5f53f58c1.png)

**Comment by MarcelSchmidberger** [comment]
As I see this issue needs to be updated, please ask me before you start working on it and use your common sense for judging which field should be changeable when.
