### ISSUE TITLE
Create a playing schedule for leagues

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#35]
**AS A** organizer of an event
**I WANT TO** have a playing schedule automatically generated based on the event configurations
**SO THAT** i know who plays with whom when

**INFO**
Generally a sport event is structured in "Spieltagen" for example the bundesliga. On each "Spieltag" everyone participating in the league has one match against an opponent. A "Spieltag" is not bound to the length of a day and can be arbitrary long. 

**ACCEPTANCE CRITERIA**
- [x] the organizer of an event should be able to access the playing schedule page
- [x] the playing schedule "Spielplan" page should display a large table which shows the "Spielpaarungen" so who plays with whom
- [x] the table should show
  - [x] an colomn which indicates the "Spieltag"
  - [x] both player/team names of the participants (**placeholde with numbers for now**)
  - [x] results ->outcome of the match for example 3:2 in football
  - [x] points -> depending on the results points for each team/player are calculated (no calculation necessary yet, manual input for the beginning)
- [x] for starters all "Spieltage" should be displayed in one big table (will be split up later on)
- [x] the "Spielpaarungen" should be based on "jeder gegen jeden" for starters (later one more match making systems)
- [x] it should be assumed that the max count of permitted players is reached all the time and if not entered is some random number for testing (this will be changed as soon as it is possible to sign up for an event)
- [x] this should work for leagues, tournaments are not necessary yet

**Comment by MarcelSchmidberger** [comment]
After a match each participating party receives points for their result. So if we have team A and team B playing a match with the result 5:10, A receives 0 Points, B 3 Points. If they draw both of them might receive 1 point. Therefore it should be possible to enter points for both parties. (The calculation of the points based on the game result is not part of the task)

**Comment by MarcelSchmidberger** [comment]
The structure of the game-days (Spieltage) needs to be refactored. On each game-day one team/player only has one match. A game day does not define a clear date for a match but rather a time span in which the match should be held. The Matches in the playing schedule should be ordered by game-day.
 

This example should help to clarify matters.

![image](https://user-images.githubusercontent.com/29160369/33269406-db1e3a66-d380-11e7-9d55-1a838858b68f.png)

https://www.ran.de/fussball/bundesliga-spielplan

**Comment by Askir** [comment]
One more question @MarcelSchmidberger is it important to distinguish between home and away teams at all? And does the matchmaking have to make it fair in terms of home matches and away matches (each team having close to the same amount of each) or is that not important right now?

**Comment by MarcelSchmidberger** [comment]
@Askir if it helps/speed up progress to neglect home and away matches, fell free to do so. There was no explicit wish from our customer, but we will ask them about this topic in the next Meeting. So you might have to implement it later on, but for now it will be fine without the distinction.

**Comment by Askir** [comment]
TODO: Fix bug that exists due to testteam creation via factorybot, see if it works with schedule with joined players.

**Comment by tobiasduerschmid** [comment]
Please add the actual size the user story was worth.

**Comment by Askir** [comment]
Actual size: XL
