### ISSUE TITLE
Enter game results in playing schedule

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#36]
**AS A** organizer of an event
**I WANT TO** enter game results and points in to the playing schedule
**SO THAT** I can keep track of the game results

**ACCEPTANCE CRITERIA**

- [x] when visiting the playing schedule there is a enter results button in each line
- [x] the button press creates a pop up form where you can enter the outcome of the match 
- [x] the form should contain
  - [x] on top the team/player name of the opponents one left, one right
  - [x] beneath that there is a field to enter the game outcome, so two number fields with a ":" between them [3]:[4]
  - [x] and a field for the points each team receives from the outcome [0]:[3]
- [x] there are save and cancel buttons to save ode discard the entered results
- [x] pressing the save or cancel buttons will close the pop up form and bring you back to the Spielplan page with the updated entries

**Comment by tobiasduerschmid** [comment]
^Please add the actual size the user story was worth.
