### ISSUE TITLE
Teams view as tiles

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#379]
**#380 depends on this for tile component**
**#374 depends on this for tile component and team logic**

New Layout for "Teams" Page:

Header and footer are out of scope.
If the team has a team-picture, then tile has this picture. If not, then we use 1 of 2 default pictures (they can be easily found by link in Flexibus channel)

In wide-screens every tile has a 25% of width with paddings/margins.
If width for content is <=800px, then it's only 2 blocks in a row. (**this is not shown in pictures**)
In it is <=400 px, then only 1 block in a row. (IT IS ONLY EXAMPLE - the most important thing, that it looks good on every screen 300 to 1600px).
Don't forget that content has max-width:1200px!

- [ ] create a reusable component for the tiles that can be used in #380.

- whole tile should be clickable
- no priority for teams
- 'Deine Teams' only shows teams that user is a member of
- 'Deine Teams' is subset of 'Alle Teams' (not disjunct)

- 'Deine Teams' block is not shown when there is no data

![teams1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fc919b2e91d2ebc3abaf51ab57f5973d047d317c05f3782387e72aba1579545f594eac42515a10adfbd82db4aa2e32db025fb28c341521842f1bbeb98a15be04bb26894f84b4ba8a48c2ea2f68.png)

![teams2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46fc919b2e91d1ebc3abaf51ab57f5973d047d317c05f3782387e72aba1579545f594eac42515a10adfbd82db4aa2e32db025fb28c341521842f1bbeb98a15be04bb26894f84b4bb884bc0e12f68.png)

**Comment by jkbe** [comment]
**Estimation: L**

**Comment by jkbe** [comment]
Some work for the tiles might've already been done in #294 that we could build on, please check with the respective team @emanuel-metzenthin @deeps96.

**Comment by emanuel-metzenthin** [comment]
@jak-ing Isn't #294 a duplicate of #380?

**Comment by MariusDanner** [comment]
@emanuel-metzenthin I thought so too, but they aren't doing design i think

> Yes just put the options for picture upload and the default image. The rest should be handled by the team of @zhamanakov :)

**Comment by jkbe** [comment]
Exactly. I just wanted to let you know because it came up in the scrum master meeting today.

**Comment by stursberg** [comment]
Important: "Players: X/Y" from mockup is now out.
Every Team-tile has a picture, name and kind of sports.

And please think, how we shorten list of kind of sports in tile in the case, if this list is tooo long.
May be only 1 (or 2) strings and then "..."

**Comment by emanuel-metzenthin** [comment]
Okay.

**Comment by stursberg** [comment]
IMPORTANT: A tile pic has to be max 100 Kb (ideally would be 50 Kb).
Quality should not suffer :)
Edit: You can use ImageMagick for this.

**Comment by stursberg** [comment]
All tiles-pics should have the same proportion:

![Screen Shot 2018-01-24 at 17.34.16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f76b7191a379e80c2855415e48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95efe4ae04555a71a3067f43b.png)

What I expect:

![2222.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46bac6c871c0cfeb9ffbb049a15ee4d6730472727957f0297487e67fbd172b575f5f4da5440c0e46adff9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abe07b2218a4685b1bd884bd2a5.png)

**Comment by stursberg** [comment]
Please make for class="tile-title": font-size: 120% (now 150%).
AND delete from class="tile-img-wrapper": height: 9em; 

A tile then looks like this:

![Screen Shot 2018-01-24 at 17.46.05.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f76b7191a379e80c2f57415f4bbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95efe4ae34950ad103e60f43b.png)

And not like now:

![Screen Shot 2018-01-24 at 17.47.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f76b7191a379e80c2f56415e47be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95efe4ae3495da21a3461f43b.png)

**Comment by stursberg** [comment]
WHY these indents?

![444.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46bcc0ce61cec1b99de6b546a749b2ce6b1326237a57a12f7280b42aea122d515f5c47a915095d15faeb9539e4e76224d50152a7842f4d7ed43c16a6b9871eb909bb228a4887b6be8c5e8d.png)

What I expect:

![6666.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46bec2cc75c0cfeb9ffbb049a15ee4d6730472727957f0297487e67fbd172b575f5f4da5440c0e46adff9b37b4f46d2ede0356b49b381d66cc2f10abb2831abe07b221894d80bfbc8f48d2a5.png)

**Comment by emanuel-metzenthin** [comment]
Because the indents look better in my opinion. At least for title and kinds of sport I would leave a small indentation to make the tiles look more like one piece.

**Comment by jkbe** [comment]
See notes from #380 that also mostly apply to this User Story: https://github.com/hpi-swt2/sport-portal/issues/380#issuecomment-361208713

**Comment by stursberg** [comment]
- [x] remove weird `-` when hovering a tile

- [x] improve tile component: no font-size in % but in rem, no fixed width, use materialize truncate instead of pure css?
- [x] increase vertical distance between picture and headline by 10px but at the same time, leave the distance between picture and description as is (so decrease distance between headline and description accordingly)

**Comment by stursberg** [comment]
why has one team different pictures?

![Screen Shot 2018-02-04 at 13.00.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f76b7191a379ec0c2b51415a48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95ff14fe44b5da31b3761f43b.png)

## Response 1
They have different pictures as you have requested i:

> If the team has a team-picture, then tile has this picture. If not, then we use 1 of 2 default pictures (they can be easily found by link in Flexibus channel)

You might have not set a team picture. Thats why it gets assigned the volleyball picture if you are a member of this team and the soccer image if it listed in "all teams".

## Zhamanakov: 
@emanuel-metzenthin @MariusDanner 
can we make that one team has always the same default pic?

**Comment by stursberg** [comment]
**[Done]** Max-width of content on page should be 1200px:
![Screen Shot 2018-02-05 at 22.14.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f66b7191a37aed0c2a55415d48be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ffe4de44f5ca21a306af43b.png)

## Leonardo
I will take care about that in #381.
