### ISSUE TITLE
Private teams are visible for everyone on teams index page

### ISSUE THREAD

**Issue by lheilmann** [hpi-swt2/sport-portal#395]
Private teams should only be visible for team members on teams index page. At the moment they are visible for non-members and unsigned user as well. 

![screen shot 2018-01-18 at 17 14 02](https://user-images.githubusercontent.com/18228544/35108173-1ab06be8-fc73-11e7-9b0b-21bbcd2bba81.png)

**Comment by jonasnoki** [comment]
This is a hotfix. Might destroy everything:
```
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy, :assign_ownership, :delete_membership, :delete_ownership, :perform_action_on_multiple_members, :assign_membership_by_email]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /teams
  def index
    multi_teams = Team.multiplayer
    if params[:filter] == "true"
      @teams = @teams - (@teams - multi_teams.includes(:team_members).where(team_users: { user_id: current_user }))
    else
      @teams = @teams - (@teams - multi_teams)
    end
  end
```

**Comment by lheilmann** [comment]
@svitlanakalancha @jonasnoki Here is the workflow I suggest regarding bugs (like this) in current sprints:
 
- We estimate the effort this issue as soon as possible. No need to estimate together will all team members - SM and developer will last.
- Issue gets assigned to a developer.
- Issue will be placed in sprint backlog with high priority.
- Developer will implement issue in current sprint as soon as possible, according to priority.
- Developer will implement other assigned issues in current sprint, as long as she/he will stay in personal sprint velocity. If other issues cannot be implemented, because personal velocity is reached, these issues stay in sprint backlog and will be implemented next sprint.

I post this suggestion here again, because the other issue is assigned to team Flexibus.

Please talk to me for remarks and/or additions.

**Comment by jonasnoki** [comment]
## Development Tasks
- [x] reproduce bug locally
- [x] add test for non-members
- [x] add test for not signed-in users
- [x] fix controller function index

**Comment by jonasnoki** [comment]
Needed time: 3h
