### ISSUE TITLE
Return button on event rankings page

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#434]
After opening table with event results, user can return to the event page. 

**Acceptance criteria**
- [ ] Table page includes button "Zurück"
- [ ] Button is linked to the correspondent event page

<img width="639" alt="screen shot 2018-01-26 at 15 45 11" src="https://user-images.githubusercontent.com/27727717/35444907-444d9082-02b0-11e8-969d-3cd8a294316f.png">

**Comment by jonasnoki** [comment]
Development tasks:
- [x] Add failing test for back button
- [x] Add back button to ranking view
