### ISSUE TITLE
User-Dashboard

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#45]
AS a user after successful log-in
I WANT to come to User-Dashboard page
TO see the most important information about upcoming events

![Screen Shot 2017-11-15 at 15.50.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f66b7191a379ea0c2e51415d49be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec958f14ee64952a7123661f43b.png)

- We DO NOT implement tables or any content of Dashboard page yet.
- Successful login => redirect user to his dashboard (for example .../my)
- There is link "My Dashboard" in User Dropdown Menu

**Comment by jkbe** [comment]
#### Estimation: M Actual: M

#### Tasks
- [x] Create dashboard page
- [x] Redirect user automatically to dashboard page on log-in
- [x] Add link to dashboard page to the user dropdown menu

**Comment by jcremerius** [comment]
The specific user dashboard can be reached by: dashboard_user_path(resource) where resource is the specific user.

**Comment by jkbe** [comment]
Waiting for user dropdown menu to be implemented by other team (#37). Maybe @deeps96 can take over this User Story since Jonas is on vacation.

**Comment by jkbe** [comment]
#37 is done so we can pick up work on this User Story again.

**Comment by deeps96** [comment]
Link to previous commits: 0ab073392a923a2bc68b67d0d3053ff4ef62c3e6 f20e5c0224e6a34d566c7ad85672a0fb67f04187

**Comment by jkbe** [comment]
*Ongoing User Story*

**Estimation: S (Actual Estimation: S)**

**Tasks**
- [x] Normal user should only be able to see his own dashboard (can't see other users' dashboards by changing the id in the URL)
- [x] Admin user can see every user's dashboard
