### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#46]
AS an admin
I WANT TO have full access to content of the sport portal
IN ORDER to have possibility to edit and delete  any information about players, teams and events

- Another users (not admins) can only delete and edit own account and events/teams that they created.
- admin can also act as normal user. For example he can create events or teams and also participate in sport events.
- enough to programmatically add **one** admin for now

**Comment by jkbe** [comment]
#### Estimation: L
#### Actual: XL

#### Tasks
- [x] Research in readme.md on access management
- [x] Add admin attribute to user model
- [x] Edit abilities for admin and other users (more subtasks if necessary)
- [x] Add admin-user to seed.rb so that admin is added automatically to every database

**Comment by emanuel-metzenthin** [comment]
TODO:

- [x] Add tests for admin usage of forbidden routes
- [x] Add permission tests for routes on users_controller
- [x] Add permission tests for views
- [x] Add controller authorization for events, teams, users
- [x] Add view authorization

**Comment by lheilmann** [comment]
@emanuel-metzenthin @MariusDanner @jak-ing Please have a look in already merged PR (https://github.com/hpi-swt2/sport-portal/pull/150) of issue #27 and still open PR (https://github.com/hpi-swt2/sport-portal/pull/130) of issue #24. Second PR already includes code of this one (https://github.com/hpi-swt2/sport-portal/pull/133) of issue #25.Please have a look in the files changed. Some of your tasks we already implemented in our team management scope. We introduced roles for (multiple) team owners and members and created abilities in the appropriate file. Besides we added controller authentication and authorization for TeamsController. Seems to me that some of the tasks overlap of work we have already done or are implementing right now. Some of the PR's are not reviewed yet/open so feel free to comment your ideas or hints.

**Comment by lheilmann** [comment]
Idea: If you create a PR on the corresponding branch of this issue with prefix WIP, we all could review the files changed and see overlapping code issues.

**Comment by emanuel-metzenthin** [comment]
Good idea. Will do so. Hopefully we are ready to open PR by tomorrow evening.

**Comment by jkbe** [comment]
*Ongoing User Story*

**Estimation: M**

**Tasks**
- [x] Unify creator and owner roles so that team owners can edit team/event settings (not just creators)
- [ ] Allow admin to edit other users' details (see new ticket #189 for details to not bloat this issue any further)

**Comment by MariusDanner** [comment]
@zhamanakov Is the event model supposed to have the creator attribute?

**Comment by stursberg** [comment]
@MariusDanner I don't really understand the question

**Comment by MariusDanner** [comment]
@zhamanakov The team ownership is defined over the owner array of team kickerz. That's why I removed the creator attribute we previously implemented. But the event model doesn't have such an attribute besides our creator attribute. So should we remove the creator attribute only on teams or on events too? I think it would be making sense to only change the team attribute. I'm only asking because the new tasklist says that we should also unify the owner/creator attributes of events, but I think there isn't such a thing as a owner attribute for events.

**Comment by emanuel-metzenthin** [comment]
@MariusDanner @zhamanakov The event definitely needs a creator because ownership of the model can't be expressed otherwise at the moment.

**Comment by lheilmann** [comment]
@MariusDanner Consider renaming the creator association in the Event-Model to owner, so at least the naming in both scopes is consistent. Cheers

On 30. Nov 2017, at 10:26, Emanuel Metzenthin <notifications@github.com<mailto:notifications@github.com>> wrote:


@MariusDanner<https://github.com/mariusdanner> @zhamanakov<https://github.com/zhamanakov> The event definitely needs a creator because ownership of the can't be expressed otherwise at the moment.

-
