### ISSUE TITLE
Default value for ranking list metrics

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#470]
**AS AN** organiser of a ranking list
**I WANT TO** have a default value for the selected metric's start value
**SO THAT** I don't have to find out what a good start value is

## ACCEPTANCE CRITERIA
- [x] When creating a new ranking list and selecting a metric in the creation form then the start value should be prefilled with a good default value (e.g. 1,000 for Elo).
- [x] When the user changes this value, switches metric and then returns to the metric he has changed the value, the new value should be displayed instead of the default value.
- [x] If the user leaves the field blank the default value should be used.

**Comment by GittiHab** [comment]
Genius!
