### ISSUE TITLE
Change wording of matches

### ISSUE THREAD

**Issue by PoJo93** [hpi-swt2/sport-portal#472]
**AS** a User
**I WANT TO** have a different wording for the settings of a Match
**TO** better understand the different fields

**ACCEPTANCE CRITERIA**

- [x] The label Gameday should be german which would be "Spieltag"
![image 2018-01-30 14 35 01](https://user-images.githubusercontent.com/5064619/35568894-c28f5c56-05ca-11e8-9852-dc458e014243.jpg)

- [x] In the properties of a game the labels should not be "Score home" and "Score away" but be the players names
![image 2018-01-30 14 31 53](https://user-images.githubusercontent.com/5064619/35568758-5211fd1c-05ca-11e8-91be-510ca035f44d.jpg)

- [x] The scores of a game should be named "Punkte". The current points should be named "Ligapunkte"
example:
![image 2018-01-30 14 32 05](https://user-images.githubusercontent.com/5064619/35568767-58a6f1aa-05ca-11e8-862f-03029d653e48.jpg)

**Comment by jkbe** [comment]
Unassigning Team Flexibus by Label so that our In Progress Column doesn't get polluted.
