### ISSUE TITLE
Small improvements in "User profile edit"

### ISSUE THREAD

**Issue by stursberg** [hpi-swt2/sport-portal#500]
- [x]  Input-text should have the same size as default text.
- [x]  Label and text-input should be in one line. 

![Screen Shot 2018-01-31 at 16.35.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e90c2854415a4ebe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95ff24ae24c5da6103467f43b.png)

- [x]  Telegram Logo should be deleted:

![Screen Shot 2018-01-31 at 16.40.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e90c2f51415d4bbe5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95ff24ae24f5da1133464f43b.png)

- [x]  Small changes in buttons from below of the page:

![Screen Shot 2018-01-31 at 16.47.37.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59fc457019d4e4001305101f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379e90c2f56415c49be5d4a1f06a3a3dc78e2a436628f0d0beed23f0b26933a43a9b8841fbf02b325df1e87e7ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ff24ae24b5ca1153262f43b.png)

**Comment by jkbe** [comment]
What do you mean with "same size as default text"? Do you mean 1.2rem?
At the moment "Vorname" is 12px, "Dmitrii" 15px and default text size for all texts on our page is 1.2rem = 18px.

--
Not "Vorname", but "Dmitrii" should have size 1.2rem (default text size).

**Comment by jkbe** [comment]
Should "Unzufrieden? ..." always break onto a new line? @zhamanakov 

--
YES.
