### ISSUE TITLE
Text adjustments in match notifications

### ISSUE THREAD

**Issue by svitlanakalancha** [hpi-swt2/sport-portal#513]
Match notifications via email should be adjusted as follows:

- each match notification contains the date and the location of the match
- each match notification contains the link to the correspondent match so that user can easily update match results.

Texts should look like this:
- a scheduled match

> Hallo `user name`,
> dein Spiel gegen `oponent team` in `event name` findet am `datum` `ort` statt.
> Viel Erfolg beim Spielen!
>`Hier` (under hier -> direct link to the match) kannst du die Ergebnisse eintragen.
>`Link to the event`

- a cancelled match

> Hallo `user name`,
> dein Spiel gegen `oponent team` in `event name` wurde am `datum` `ort` abgesagt.
> Viel Erfolg!
>`Hier` (under hier -> direct link to the match) kannst du die Änderungen vornehmen.
>`Link to the event`

- a postponed match

> Hallo `user name`,
> dein Spiel gegen `oponent team` in `event name` wurde am `datum` `ort` verschoben.
> Viel Erfolg beim Spielen!
>`Hier` (under hier -> direct link to the match) kannst du die Ergebnisse eintragen.
>`Link to the event`

**Comment by lheilmann** [comment]
**Needs clarification:**
- [x] What's the deal with the following match notification? @svitlanakalancha 

> Hallo admin,
> dein Spiel (A vs. B) im Event Bundesliga startet morgen um Montag, 05. Februar 2018, 00:00 Uhr. Ihr trefft euch am folgenden Ort: C
>
>Viel Erfolg beim Training!
>
>Bundesliga

**Development tasks:**
- [x] Adjust `.html` files:
   - `match_scheduled.html.erb`
   - `match_canceled.html.erb`
   - `match_date_changed.html.erb`
- [x] Adjust `.text` files:
   - `match_scheduled.text.erb`
   - `match_canceled.text.erb`
   - `match_date_changed.text.erb`

**Comment by lheilmann** [comment]
**ToDo's**:
- [x] Calculate opponent team
- [x] Check if place is present in mail template
- [x] Add translation for 'Hier'
- [ ] Fix template errors
- [x] Add `en` locales

**Comment by svitlanakalancha** [comment]
@lheilmann as I recently found out, another team was working on match notifications @nikriek can you help us with it?

Besides, our client wanted to have not only the date of the match, but also location and the direct link to the correspondent match. This was not implemented in our kickerz version of notifications #308

**Comment by nikriek** [comment]
jep, I built the match notification. the ticket is not yet approved by the PM (@PoJo93) due to a missing GUI for testing. what do you need from me?

**Comment by svitlanakalancha** [comment]
@nikriek our team has already implemented match notifications which are merged in dev. So I suppose, some mismatches may occur if we have two versions of such notifications.
@lheilmann can you check it, please?

**Comment by lheilmann** [comment]
@nikriek Please have a look at #308 & #307 before merging your stuff into `dev`. Are there any duplicate implementations? If so, we should have a chat with @tomkellog and @jonasnoki.

@svitlanakalancha I have already added `place` of match and links to the correspondent match regarding this issue. There are still some minor things to do before I am able to create a PR for this piece of code.

**Comment by nikriek** [comment]
The ticket is already merged

**Comment by nikriek** [comment]
https://github.com/hpi-swt2/sport-portal/pull/267

**Comment by lheilmann** [comment]
@nikriek Okay then I assume the `match_notification` is built by you (as I could see in your already closed PR) while the other mail templates: `match_scheduled`, `match_canceled` and `match_date_changed` are built by our team?!

**Comment by nikriek** [comment]
Yes

**Comment by lheilmann** [comment]
@nikriek Alright, thanks for clarification! 

@svitlanakalancha Scope is clear for me now. :+1:

**Comment by lheilmann** [comment]
@svitlanakalancha The attribute `place` and `start_time` of `Match` class can be `NULL`. What should be displayed in the mail templates in this case? 

Here's the `place` missing:
![screen shot 2018-02-05 at 20 27 58](https://user-images.githubusercontent.com/18228544/35825520-6330c42a-0ab6-11e8-85c5-0803f1861bbf.png)

In my mind there are **three** options:

- Use placeholders for missing `place` and `start_time` - might be the easiest way to implement.
- Cut out `in <place>` and `am <start_date> um <start_time>` - might be the most elegant option, but more complex code-wise!
- Cut out `place` and `start_time` from the sentence above and append the following lines to the first sentence:
  ```
  Where? <place>
  When? <start_date> <start_time>
  ```
- Don't care and leave it like that - not quite elegant!

**Comment by lheilmann** [comment]
@svitlanakalancha I personally like option 3 the most, because it's only slightly more complex code-wise than option 1 and elegant I would think. :smiley_cat:

**Comment by lheilmann** [comment]
@svitlanakalancha Please also provide subjects for the mails `match_scheduled`, `match_canceled` and `match_date_changed`. In my mind they should not be too long and only contain the most important information.

**Comment by svitlanakalancha** [comment]
@lheilmann if I understood you correctly, the option 3 will look like this:

> Hallo Lukas,
> dein Spiel gegen `Jakob `im Event `Superliga` wurde abgesagt.
> Wann: `date`
> Wo: `location`
> Viel Erfolg!

If yes, I am ok with it :) Can we convert all match messages to this form then?

**Comment by svitlanakalancha** [comment]
@lheilmann in my opinion, old subjects are ok, meaning 
"Dein Match wurde geplant/verschoben/abgesagt/"

**Comment by lheilmann** [comment]
@svitlanakalancha Great, thanks! :+1:

**Comment by lheilmann** [comment]
**ToDo's**
- [x] Think about how to test the calculation of opponent team and implement it! Then all tests should be fixed...
- [x] Fix this one damn bug that occurs when rendering this one damn link in the mail templates.
- [x] Re-check acceptance criteria and test locally.

**Comment by lheilmann** [comment]
@svitlanakalancha Mail subjects should end with a `.` or without? @bakoe

**Comment by svitlanakalancha** [comment]
I'd say without @lheilmann

**Comment by lheilmann** [comment]
Hey @svitlanakalancha, here are some minor thoughts of the code reviewers @bakoe and @tomkellog: 

<img width="666" alt="screen shot 2018-02-07 at 12 26 02" src="https://user-images.githubusercontent.com/18228544/35914222-cb199e2a-0c02-11e8-8ba7-e8a45ca70221.png">
<img width="668" alt="screen shot 2018-02-07 at 12 26 47" src="https://user-images.githubusercontent.com/18228544/35914223-cb46ca8a-0c02-11e8-9401-d556271605b1.png">
<img width="668" alt="screen shot 2018-02-07 at 12 27 15" src="https://user-images.githubusercontent.com/18228544/35914224-cb6a43ac-0c02-11e8-915c-ef31d337cc1a.png">
<img width="665" alt="screen shot 2018-02-07 at 12 27 56" src="https://user-images.githubusercontent.com/18228544/35914225-cb966dd8-0c02-11e8-8bfa-6f4795652d17.png">

Please have a quick look on these ideas. We then might merge this issue in `develop` before our meeting.

**Comment by svitlanakalancha** [comment]
@lheilmann when match is canceled, in my opinion "Viel Erfolg" as well as " Have fun" sounds ok, because the match will take place anyway. 
"Findet bald statt" sounds good to me.
"Viel Erfolg beim Sport" is also ok, if you think it has more meaning in German. 
Thank you!

**Comment by lheilmann** [comment]
@svitlanakalancha Alright, thanks!
