### ISSUE TITLE
Remove unnecessary buttons from playing schedule

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#524]
`Spielplan` page contains unnecessary buttons which confuse a user. This story only affects the design of the page, not its functionality.

**Acceptance Criteria**

- [ ] remove `Löschen` button
- [ ] remove `Bearbeiten` button
- [ ] rename `Anzeigen` button to `Ergebnisse eintragen`

![image](https://user-images.githubusercontent.com/29160369/35772363-0d89db44-093d-11e8-8916-df62f8fcac72.png)

**Comment by birneamstiel** [comment]
In consultation with @svitlanakalancha: changes affect both `Tournaments` and `Leagues`
