### ISSUE TITLE
Deadline for events

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#53]
**AS AN** organiser of an event
**I WANT TO** enter a deadline for signing up to an event when creating one
**SO THAT** the users know until when to sign up and to prevent late registrations

## Acceptance Criteria
- [ ] users can only join the event if the deadline has not passed
- [x] you can enter a deadline for signing up for an event
- [x] the selection of the dates should be possible either by entering the numbers, or by selecting them from a calendar view similar to [https://www.bahn.de/p/view/index.shtml](url)

**Comment by GittiHab** [comment]
Reviewed by Product Owner and accepted
