### ISSUE TITLE
Fancy calendar picker when setting start and end date

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#54]
**AS AN** organisor of an event
**I WANT TO** I want to be able to select the start and end date in the same calendar
**SO THAT** I don't have to click around so much

## ACCEPTANCE CRITERIA
- [ ] If there are durations (start and end date), after clicking on the first date in the calendar for the start of an event, you can select the end with a second click in the same calendar. For example on [Swoodoo](https://www.swoodoo.com/)
- [ ] The days between are highlighted for durations
- [ ] After I selected the last possible date, the calendar should be hidden
- [ ] If the date field is empty, the calendar picker should preselect the current date as the default date.
