### ISSUE TITLE
Mail verification: confirmation Emails

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#57]
**As an** admin
**I want** my plattform **to** send my users e-mails when they change their account settings
**In order to** add an additional layer of security / prevent account theft

**Acceptance Criteria**:
- [ ] Confirmation mails on: 
 - changing e-mail and deleting the account
 - command execution after clicking the confirmation links 
- [x] notification mails on changing passwords
- should be expendable if other crucial data is added to the platform

**Tasks**:
- [x] find out how to send mails
- [x] templates
- [x] send notification mails
- [ ] send confirmation mails with working confirmation link
