### ISSUE TITLE
Open ID integration: linking accounts

### ISSUE THREAD

**Issue by MerlindlH** [hpi-swt2/sport-portal#59]
**As a** registered user with OpenIDAccount
**I want to** connect my plattform-Account with openID
**In order to** simplify my login process

**Acceptance criteria**:
- [x] the account settings page should have a "connect to openID"-button
- [x] one OpenID Account cannot be linked to two users

**Tasks:**
- [ ] research
- [ ] model adjustments
- [ ] implement platform Account + opeinID connection

**Comment by fpottbaecker** [comment]
Estimated size: 8 (Unit: 30min)
Actual size: 9 (4.5h)
