### ISSUE TITLE
Join an event as single player

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#85]
**AS AN** logged in user
**I WANT TO** be able to join non-team events
**SO THAT** I can participate in events

## ACCEPTANCE CRITERIA
- [x] On the _all events_ page, if an event is not a team sport there should be a button "join"
- [x] On the detailed page of an event there should be a "join" button if the event is not a team sport
- After the join buttons has been clicked
  - [x] The button should change to "leave event"
  - [x] The user should have joined the event
  - [x] The event should be labeled with "Participating"
- [x] Every time the user opens the _all events_ page all events he has joined should be labeled with "Participating"
- [x] The "join" button is only visible as long as the deadline has not passed
- [x] Only logged in users can join events

**Comment by GittiHab** [comment]
Sorry, if this was not clear but, of course, if the user has clicked the "leave event" button then the user should have left the event:

  - [x] When the "leave event" button has been clicked and it was enabled the player should leave the event and it should not be labeled "Participating" anymore

**Comment by sumpfranze** [comment]
Are single user joins going to be implemented as one-member teams in the background? Because that would simplify the associations between the event and team model (event/user association participants could be removed). This will be important for User story #89

**Comment by ConstantinLange** [comment]
We recognized a mistake with one requirement of this User Story:
If the deadline has passed you can still join the event, if you show all events via the checkbox. The test does not catch this case and therefore the test should be changed and the functionality has to be implemented.

**Comment by GittiHab** [comment]
@jacobfreise As discussed in the meeting the customer would like to only have teams and not distinguish between single and team players.

@ConstantinLange Do you really mean a **mistake** in the user story or do you mean **unfulfilled** requirement? There is indeed a requirement *The "join" button is only visible as long as the deadline has not passed* which is currently not fulfilled (as you stated, if you press the *show all events* checkbox one can still join)
