### ISSUE TITLE
Support first-come-first-serve

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#86]
**AS AN** organiser of an event
**I WANT TO** be able to enable a first-come-first-serve option for my events with limited participants
**SO THAT** there is a selection process for events with limited places

## ACCEPTANCE CRITERIA
requires #85 
- [x] When creating or editing an (own) event I can choose the selection process
- [x] There is one option for the selection process called "first come first serve"
- When this option is enabled and there is a player count then
  - [x] As long as the player count is not reached, a team or player who wants to join the event is immediately registered for the event
  - [x] If the player count is reached the join function is disabled and the button is greyed out
  - [ ] and the event is labeled as "full"

**Comment by GittiHab** [comment]
Please remove the non-existing selection processes from the dropdown in the event settings. Basically hide the dropdown as long as there are no other processes.
<img width="887" alt="screen shot 2018-01-18 at 14 32 01" src="https://user-images.githubusercontent.com/6453623/35100505-5e1ec6c0-fc5c-11e7-8601-a8484547b6ef.png">

**Comment by GittiHab** [comment]
The dropdown is not fully hidden but I guess it is best to focus on the other tasks.
