### ISSUE TITLE
Allow first-come-first-serve queue

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#87]
**AS A** player or team
**I WANT TO** be able to join a queue for an event with limited places
**SO THAT** I can be added to the event as soon as place gets available

## ACCEPTANCE CRITERIA
For events which have a player count and the selection process is _first come first serve_ (see #86):  
- [ ] If the player count is reached there is no join button but a button "Join Queue"
- [ ] If a team or player wants to join the event they are added to a queue
    - [ ] and the button changes to "leave queue"
    - [ ] the event is labeled as "In Queue"
    - [ ] If someone leaves the event before the deadline the next team/player in the queue is automatically registered to the event and receives an e-mail that they are now registered
    - [ ] If the player/team press the "leave queue" button they are removed from the queue and the label is also removed
