### ISSUE TITLE
Support selection by organiser

### ISSUE THREAD

**Issue by GittiHab** [hpi-swt2/sport-portal#88]
**AS AN** organiser of an event
**I WANT TO** be able to enable select the participants for my events with limited participants
**SO THAT** there is a selection process for events with limited places

## ACCEPTANCE CRITERIA
requires #85 
- [ ] When creating or editing an (own) event I can choose the selection process
- [ ] There is one option for the selection process called "Selection by organiser"
- When this option is enabled and there is a player count then
  - [ ] There is no "join" button but a button "request" for the events
  - [ ] The player/team can request to join the event by clicking the button
  - [ ] If the player/team requested to join the event then the event is labeled as "Waiting for organiser"
- [ ] When the organiser views the detailed page of his event he sees a list of all players/teams who requested to participate
- [ ] The organiser can press a button "Add to event" to register a team/player in the list
- [ ] If the organiser registers a team/player they receive an e-mail notification that they have joined the event and they are now participants of the event
