### ISSUE TITLE
redesign create new event page UI

### ISSUE THREAD

**Issue by MarcelSchmidberger** [hpi-swt2/sport-portal#95]
As a user a
I want to be guided when creating an new event and do it in an easy and intuitive fashion
In order to be able to create a new event without problems from the get go
 
**Acceptance criteria:**
**General:**
- [ ] The create new event page should fit the visual style of the plattform.
- [ ] The event creation should be structured in 3 parts General, config1, config2
- [ ] Page switch buttons should work

**Page1: "Erstelle einen neuen Event"**

- [ ] Event art should be a switch button, the activated one is highlighted

**Page2: "Konfiguriere dein Spielsystem"**

- [ ] should appear if Liga is selected in page 1
- [ ] should appear when clicking "weiter" from page 1
- [ ] has dropdown menu for "Spielsystem" with the option "jeder gegen jeden"
- [ ] enter games per "Spieltag" for example for best of 5, slider and field mirror each other  

**Page3: "Konfiguriere deine Liga"**

- [ ] should appear if Liga is selected in page 1
- [ ] Teilnehmerzahl can be entered either with the slider or the text field and they manipulate each other
- [ ] Event begin can be selected from the calender (as existing)
- [ ] choosing the Event begin sets the Anmeldeschluss
- [ ] Anmeldeschluss can not be after Event begin
- [ ] based on "Spielsystem(jeder gegen jeden)" and "Länge eines Spieltages" the "nötige Spieltage" count to determine a winner with the system is calculated and displayed. 
- [ ] the expected finishing date is displayed

**Page1: "Erstelle einen neuen Event"**

![image](https://user-images.githubusercontent.com/29160369/33050302-86581040-ce64-11e7-9367-f0e930ad4770.png)

**Page2: "Konfiguriere dein Spielsystem"**

![image](https://user-images.githubusercontent.com/29160369/33050330-a7334a14-ce64-11e7-8b98-4a6df0d8d3ff.png)

**Page3: "Konfiguriere deine Liga"**

![image](https://user-images.githubusercontent.com/29160369/33050313-9412ec8c-ce64-11e7-9d16-24b3987f1ebb.png)

**Comment by MarcelSchmidberger** [comment]
this is depricated
